// =====================================================================
// THE WAYWARD COMPANY — 2024 PHB ITEM CATALOG
// ---------------------------------------------------------------------
// Curated list of items available to the party for the inventory picker.
// Not exhaustive — starter set covers all standard weapons + armor +
// essential gear + party-relevant magic items. Add more on demand.
//
// Each entry:
//   id          — unique key (snake_case)
//   name        — display name
//   category    — 'weapon' | 'armor' | 'gear' | 'tool' | 'consumable' | 'magic'
//   subcategory — for grouping in picker (e.g. 'simple_melee', 'light_armor')
//   cost        — display string (e.g. '15 gp')
//   weight      — number in pounds
//   description — full text (mechanics + flavour)
//   properties  — array of tag strings (weapons only)
//   damage      — dice string (weapons only)
//   ac          — string (armor only, e.g. '11 + Dex')
//   stealthDisadv — bool (armor only)
//   strReq      — number (armor only, if strength required)
//   attunement  — bool (magic items only)
//   source      — page reference
// =====================================================================

const ITEMS_2024 = [

  // =================================================================
  // SIMPLE MELEE WEAPONS
  // =================================================================
  { id: 'club', name: 'Club', category: 'weapon', subcategory: 'simple_melee',
    cost: '1 sp', weight: 2, damage: '1d4 bludgeoning', properties: ['Light'],
    mastery: 'Slow',
    description: 'A wooden bludgeon. Simple weapon, one-handed. Damage 1d4 bludgeoning. Weapon Mastery: Slow (target\'s Speed reduced by 10 ft. until start of your next turn).',
    source: 'PHB 2024 p.213' },
  { id: 'dagger', name: 'Dagger', category: 'weapon', subcategory: 'simple_melee',
    cost: '2 gp', weight: 1, damage: '1d4 piercing', properties: ['Finesse', 'Light', 'Thrown (20/60)'],
    mastery: 'Nick',
    description: 'A short blade. Simple weapon. Damage 1d4 piercing. Finesse (use STR or DEX), Light, Thrown (20/60 ft). Mastery: Nick (extra light-weapon attack replaces the bonus-action attack, made as part of the Attack action).',
    source: 'PHB 2024 p.213' },
  { id: 'greatclub', name: 'Greatclub', category: 'weapon', subcategory: 'simple_melee',
    cost: '2 sp', weight: 10, damage: '1d8 bludgeoning', properties: ['Two-Handed'],
    mastery: 'Push',
    description: 'A massive wooden bludgeon. Simple two-handed weapon. Damage 1d8 bludgeoning. Mastery: Push (Large or smaller target pushed up to 10 ft. straight away from you).',
    source: 'PHB 2024 p.213' },
  { id: 'handaxe', name: 'Handaxe', category: 'weapon', subcategory: 'simple_melee',
    cost: '5 gp', weight: 2, damage: '1d6 slashing', properties: ['Light', 'Thrown (20/60)'],
    mastery: 'Vex',
    description: 'A single-handed throwing axe. Simple weapon. Damage 1d6 slashing. Light, Thrown (20/60 ft). Mastery: Vex (on a hit, you have Advantage on your next attack roll against the target before end of your next turn).',
    source: 'PHB 2024 p.213' },
  { id: 'javelin', name: 'Javelin', category: 'weapon', subcategory: 'simple_melee',
    cost: '5 sp', weight: 2, damage: '1d6 piercing', properties: ['Thrown (30/120)'],
    mastery: 'Slow',
    description: 'A throwing spear. Simple weapon. Damage 1d6 piercing. Thrown (30/120 ft). Mastery: Slow.',
    source: 'PHB 2024 p.213' },
  { id: 'light_hammer', name: 'Light Hammer', category: 'weapon', subcategory: 'simple_melee',
    cost: '2 gp', weight: 2, damage: '1d4 bludgeoning', properties: ['Light', 'Thrown (20/60)'],
    mastery: 'Nick',
    description: 'A small hammer. Simple weapon. Damage 1d4 bludgeoning. Light, Thrown (20/60 ft). Mastery: Nick.',
    source: 'PHB 2024 p.213' },
  { id: 'mace', name: 'Mace', category: 'weapon', subcategory: 'simple_melee',
    cost: '5 gp', weight: 4, damage: '1d6 bludgeoning', properties: [],
    mastery: 'Sap',
    description: 'A metal-headed bludgeon. Simple weapon. Damage 1d6 bludgeoning. Mastery: Sap (on a hit, the target has Disadvantage on its next attack roll before start of your next turn).',
    source: 'PHB 2024 p.213' },
  { id: 'quarterstaff', name: 'Quarterstaff', category: 'weapon', subcategory: 'simple_melee',
    cost: '2 sp', weight: 4, damage: '1d6 bludgeoning', properties: ['Versatile (1d8)'],
    mastery: 'Topple',
    description: 'A long wooden staff. Simple weapon. Damage 1d6 bludgeoning (or 1d8 two-handed). Mastery: Topple (target must make CON save or gain Prone).',
    source: 'PHB 2024 p.213' },
  { id: 'sickle', name: 'Sickle', category: 'weapon', subcategory: 'simple_melee',
    cost: '1 gp', weight: 2, damage: '1d4 slashing', properties: ['Light'],
    mastery: 'Nick',
    description: 'A curved short blade. Simple weapon. Damage 1d4 slashing. Light. Mastery: Nick.',
    source: 'PHB 2024 p.213' },
  { id: 'spear', name: 'Spear', category: 'weapon', subcategory: 'simple_melee',
    cost: '1 gp', weight: 3, damage: '1d6 piercing', properties: ['Thrown (20/60)', 'Versatile (1d8)'],
    mastery: 'Sap',
    description: 'A thrusting or throwing polearm. Simple weapon. Damage 1d6 piercing (or 1d8 two-handed). Thrown (20/60 ft). Mastery: Sap.',
    source: 'PHB 2024 p.213' },

  // =================================================================
  // SIMPLE RANGED WEAPONS
  // =================================================================
  { id: 'dart', name: 'Dart', category: 'weapon', subcategory: 'simple_ranged',
    cost: '5 cp', weight: 0.25, damage: '1d4 piercing', properties: ['Finesse', 'Thrown (20/60)'],
    mastery: 'Vex',
    description: 'A small throwing spike. Simple ranged. Damage 1d4 piercing. Finesse, Thrown (20/60 ft). Mastery: Vex.',
    source: 'PHB 2024 p.213' },
  { id: 'light_crossbow', name: 'Light Crossbow', category: 'weapon', subcategory: 'simple_ranged',
    cost: '25 gp', weight: 5, damage: '1d8 piercing', properties: ['Ammunition (80/320)', 'Loading', 'Two-Handed'],
    mastery: 'Slow',
    description: 'A crossbow requiring both hands. Simple ranged. Damage 1d8 piercing. Ammunition (80/320 ft), Loading (one shot per action, bonus action, or reaction), Two-Handed. Mastery: Slow.',
    source: 'PHB 2024 p.213' },
  { id: 'shortbow', name: 'Shortbow', category: 'weapon', subcategory: 'simple_ranged',
    cost: '25 gp', weight: 2, damage: '1d6 piercing', properties: ['Ammunition (80/320)', 'Two-Handed'],
    mastery: 'Vex',
    description: 'A short bow. Simple ranged. Damage 1d6 piercing. Ammunition (80/320 ft), Two-Handed. Mastery: Vex.',
    source: 'PHB 2024 p.213' },
  { id: 'sling', name: 'Sling', category: 'weapon', subcategory: 'simple_ranged',
    cost: '1 sp', weight: 0, damage: '1d4 bludgeoning', properties: ['Ammunition (30/120)'],
    mastery: 'Slow',
    description: 'A leather sling for stones. Simple ranged. Damage 1d4 bludgeoning. Ammunition (30/120 ft). Mastery: Slow.',
    source: 'PHB 2024 p.213' },

  // =================================================================
  // MARTIAL MELEE WEAPONS
  // =================================================================
  { id: 'battleaxe', name: 'Battleaxe', category: 'weapon', subcategory: 'martial_melee',
    cost: '10 gp', weight: 4, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    mastery: 'Topple',
    description: 'A single-bladed axe. Martial weapon. Damage 1d8 slashing (1d10 two-handed). Mastery: Topple.',
    source: 'PHB 2024 p.213' },
  { id: 'flail', name: 'Flail', category: 'weapon', subcategory: 'martial_melee',
    cost: '10 gp', weight: 2, damage: '1d8 bludgeoning', properties: [],
    mastery: 'Sap',
    description: 'A hinged weight on a haft. Martial weapon. Damage 1d8 bludgeoning. Mastery: Sap.',
    source: 'PHB 2024 p.213' },
  { id: 'glaive', name: 'Glaive', category: 'weapon', subcategory: 'martial_melee',
    cost: '20 gp', weight: 6, damage: '1d10 slashing', properties: ['Heavy', 'Reach', 'Two-Handed'],
    mastery: 'Graze',
    description: 'A long-bladed polearm. Martial two-handed weapon. Damage 1d10 slashing. Heavy, Reach (10 ft). Mastery: Graze (on a miss, target takes damage equal to your ability modifier).',
    source: 'PHB 2024 p.213' },
  { id: 'greataxe', name: 'Greataxe', category: 'weapon', subcategory: 'martial_melee',
    cost: '30 gp', weight: 7, damage: '1d12 slashing', properties: ['Heavy', 'Two-Handed'],
    mastery: 'Cleave',
    description: 'A massive two-handed axe. Martial two-handed weapon. Damage 1d12 slashing. Heavy. Mastery: Cleave (on a hit against a target, make an additional attack roll against a second creature within 5 ft. and within reach; same modifiers).',
    source: 'PHB 2024 p.213' },
  { id: 'greatsword', name: 'Greatsword', category: 'weapon', subcategory: 'martial_melee',
    cost: '50 gp', weight: 6, damage: '2d6 slashing', properties: ['Heavy', 'Two-Handed'],
    mastery: 'Graze',
    description: 'A massive two-handed sword. Martial two-handed weapon. Damage 2d6 slashing. Heavy. Mastery: Graze.',
    source: 'PHB 2024 p.213' },
  { id: 'halberd', name: 'Halberd', category: 'weapon', subcategory: 'martial_melee',
    cost: '20 gp', weight: 6, damage: '1d10 slashing', properties: ['Heavy', 'Reach', 'Two-Handed'],
    mastery: 'Cleave',
    description: 'A single-edged axe on a long haft. Martial two-handed weapon. Damage 1d10 slashing. Heavy, Reach. Mastery: Cleave.',
    source: 'PHB 2024 p.213' },
  { id: 'lance', name: 'Lance', category: 'weapon', subcategory: 'martial_melee',
    cost: '10 gp', weight: 6, damage: '1d10 piercing', properties: ['Heavy', 'Reach', 'Special'],
    mastery: 'Topple',
    description: 'A long thrusting weapon typically used from horseback. Martial weapon. Damage 1d10 piercing. Heavy, Reach. Special: you have Disadvantage on attacks with a lance when your target is within 5 ft. of you. Mastery: Topple.',
    source: 'PHB 2024 p.213' },
  { id: 'longsword', name: 'Longsword', category: 'weapon', subcategory: 'martial_melee',
    cost: '15 gp', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    mastery: 'Sap',
    description: 'A straight-bladed sword. Martial weapon. Damage 1d8 slashing (1d10 two-handed). Mastery: Sap.',
    source: 'PHB 2024 p.213' },
  { id: 'maul', name: 'Maul', category: 'weapon', subcategory: 'martial_melee',
    cost: '10 gp', weight: 10, damage: '2d6 bludgeoning', properties: ['Heavy', 'Two-Handed'],
    mastery: 'Topple',
    description: 'A massive two-handed hammer. Martial two-handed weapon. Damage 2d6 bludgeoning. Heavy. Mastery: Topple.',
    source: 'PHB 2024 p.213' },
  { id: 'morningstar', name: 'Morningstar', category: 'weapon', subcategory: 'martial_melee',
    cost: '15 gp', weight: 4, damage: '1d8 piercing', properties: [],
    mastery: 'Sap',
    description: 'A spiked bludgeon. Martial weapon. Damage 1d8 piercing. Mastery: Sap.',
    source: 'PHB 2024 p.213' },
  { id: 'pike', name: 'Pike', category: 'weapon', subcategory: 'martial_melee',
    cost: '5 gp', weight: 18, damage: '1d10 piercing', properties: ['Heavy', 'Reach', 'Two-Handed'],
    mastery: 'Push',
    description: 'A long infantry spear. Martial two-handed weapon. Damage 1d10 piercing. Heavy, Reach. Mastery: Push.',
    source: 'PHB 2024 p.213' },
  { id: 'rapier', name: 'Rapier', category: 'weapon', subcategory: 'martial_melee',
    cost: '25 gp', weight: 2, damage: '1d8 piercing', properties: ['Finesse'],
    mastery: 'Vex',
    description: 'A thin thrusting sword. Martial weapon. Damage 1d8 piercing. Finesse. Mastery: Vex.',
    source: 'PHB 2024 p.213' },
  { id: 'scimitar', name: 'Scimitar', category: 'weapon', subcategory: 'martial_melee',
    cost: '25 gp', weight: 3, damage: '1d6 slashing', properties: ['Finesse', 'Light'],
    mastery: 'Nick',
    description: 'A curved slashing sword. Martial weapon. Damage 1d6 slashing. Finesse, Light. Mastery: Nick.',
    source: 'PHB 2024 p.213' },
  { id: 'shortsword', name: 'Shortsword', category: 'weapon', subcategory: 'martial_melee',
    cost: '10 gp', weight: 2, damage: '1d6 piercing', properties: ['Finesse', 'Light'],
    mastery: 'Vex',
    description: 'A short thrusting sword. Martial weapon. Damage 1d6 piercing. Finesse, Light. Mastery: Vex.',
    source: 'PHB 2024 p.213' },
  { id: 'trident', name: 'Trident', category: 'weapon', subcategory: 'martial_melee',
    cost: '5 gp', weight: 4, damage: '1d8 piercing', properties: ['Thrown (20/60)', 'Versatile (1d10)'],
    mastery: 'Topple',
    description: 'A three-pronged spear. Martial weapon. Damage 1d8 piercing (1d10 two-handed). Thrown (20/60 ft). Mastery: Topple.',
    source: 'PHB 2024 p.213' },
  { id: 'warhammer', name: 'Warhammer', category: 'weapon', subcategory: 'martial_melee',
    cost: '15 gp', weight: 2, damage: '1d8 bludgeoning', properties: ['Versatile (1d10)'],
    mastery: 'Push',
    description: 'A single-handed war hammer. Martial weapon. Damage 1d8 bludgeoning (1d10 two-handed). Mastery: Push.',
    source: 'PHB 2024 p.213' },
  { id: 'war_pick', name: 'War Pick', category: 'weapon', subcategory: 'martial_melee',
    cost: '5 gp', weight: 2, damage: '1d8 piercing', properties: ['Versatile (1d10)'],
    mastery: 'Sap',
    description: 'A curved single-handed pick. Martial weapon. Damage 1d8 piercing (1d10 two-handed). Mastery: Sap.',
    source: 'PHB 2024 p.213' },
  { id: 'whip', name: 'Whip', category: 'weapon', subcategory: 'martial_melee',
    cost: '2 gp', weight: 3, damage: '1d4 slashing', properties: ['Finesse', 'Reach'],
    mastery: 'Slow',
    description: 'A long lashing whip. Martial weapon. Damage 1d4 slashing. Finesse, Reach (10 ft). Mastery: Slow.',
    source: 'PHB 2024 p.213' },

  // =================================================================
  // MARTIAL RANGED WEAPONS
  // =================================================================
  { id: 'blowgun', name: 'Blowgun', category: 'weapon', subcategory: 'martial_ranged',
    cost: '10 gp', weight: 1, damage: '1 piercing', properties: ['Ammunition (25/100)', 'Loading'],
    mastery: 'Vex',
    description: 'A hollow tube for firing darts. Martial ranged. Damage 1 piercing. Ammunition (25/100 ft), Loading. Mastery: Vex.',
    source: 'PHB 2024 p.213' },
  { id: 'hand_crossbow', name: 'Hand Crossbow', category: 'weapon', subcategory: 'martial_ranged',
    cost: '75 gp', weight: 3, damage: '1d6 piercing', properties: ['Ammunition (30/120)', 'Light', 'Loading'],
    mastery: 'Vex',
    description: 'A one-handed crossbow. Martial ranged. Damage 1d6 piercing. Ammunition (30/120 ft), Light, Loading. Mastery: Vex.',
    source: 'PHB 2024 p.213' },
  { id: 'heavy_crossbow', name: 'Heavy Crossbow', category: 'weapon', subcategory: 'martial_ranged',
    cost: '50 gp', weight: 18, damage: '1d10 piercing', properties: ['Ammunition (100/400)', 'Heavy', 'Loading', 'Two-Handed'],
    mastery: 'Push',
    description: 'A heavy two-handed crossbow. Martial ranged. Damage 1d10 piercing. Ammunition (100/400 ft), Heavy, Loading, Two-Handed. Mastery: Push.',
    source: 'PHB 2024 p.213' },
  { id: 'longbow', name: 'Longbow', category: 'weapon', subcategory: 'martial_ranged',
    cost: '50 gp', weight: 2, damage: '1d8 piercing', properties: ['Ammunition (150/600)', 'Heavy', 'Two-Handed'],
    mastery: 'Slow',
    description: 'A tall powerful bow. Martial ranged. Damage 1d8 piercing. Ammunition (150/600 ft), Heavy, Two-Handed. Mastery: Slow.',
    source: 'PHB 2024 p.213' },
  { id: 'musket', name: 'Musket', category: 'weapon', subcategory: 'martial_ranged',
    cost: '500 gp', weight: 10, damage: '1d12 piercing', properties: ['Ammunition (40/120)', 'Loading', 'Two-Handed'],
    mastery: 'Slow',
    description: 'A firearm (DM discretion — not standard in every campaign). Martial ranged. Damage 1d12 piercing. Ammunition (40/120 ft), Loading, Two-Handed. Mastery: Slow.',
    source: 'PHB 2024 p.213 (optional)' },
  { id: 'pistol', name: 'Pistol', category: 'weapon', subcategory: 'martial_ranged',
    cost: '250 gp', weight: 3, damage: '1d10 piercing', properties: ['Ammunition (30/90)', 'Loading'],
    mastery: 'Vex',
    description: 'A firearm (DM discretion). Martial ranged. Damage 1d10 piercing. Ammunition (30/90 ft), Loading. Mastery: Vex.',
    source: 'PHB 2024 p.213 (optional)' },

  // =================================================================
  // LIGHT ARMOR
  // =================================================================
  { id: 'padded', name: 'Padded Armor', category: 'armor', subcategory: 'light_armor',
    cost: '5 gp', weight: 8, ac: '11 + Dex', stealthDisadv: true,
    description: 'Quilted layers of cloth and batting. Light armor. AC 11 + Dex modifier. Stealth Disadvantage. Don 1 minute / doff 1 minute.',
    source: 'PHB 2024 p.216' },
  { id: 'leather', name: 'Leather Armor', category: 'armor', subcategory: 'light_armor',
    cost: '10 gp', weight: 10, ac: '11 + Dex', stealthDisadv: false,
    description: 'Boiled and treated hide. Light armor. AC 11 + Dex modifier. Don 1 min / doff 1 min.',
    source: 'PHB 2024 p.216' },
  { id: 'studded_leather', name: 'Studded Leather Armor', category: 'armor', subcategory: 'light_armor',
    cost: '45 gp', weight: 13, ac: '12 + Dex', stealthDisadv: false,
    description: 'Leather reinforced with metal rivets. Light armor. AC 12 + Dex modifier. Don 1 min / doff 1 min.',
    source: 'PHB 2024 p.216' },

  // =================================================================
  // MEDIUM ARMOR
  // =================================================================
  { id: 'hide', name: 'Hide Armor', category: 'armor', subcategory: 'medium_armor',
    cost: '10 gp', weight: 12, ac: '12 + Dex (max 2)', stealthDisadv: false,
    description: 'Thick furs and pelts. Medium armor. AC 12 + Dex (max +2). Don 5 min / doff 1 min.',
    source: 'PHB 2024 p.216' },
  { id: 'chain_shirt', name: 'Chain Shirt', category: 'armor', subcategory: 'medium_armor',
    cost: '50 gp', weight: 20, ac: '13 + Dex (max 2)', stealthDisadv: false,
    description: 'Metal rings worn over cloth. Medium armor. AC 13 + Dex (max +2). Don 5 min / doff 1 min.',
    source: 'PHB 2024 p.216' },
  { id: 'scale_mail', name: 'Scale Mail', category: 'armor', subcategory: 'medium_armor',
    cost: '50 gp', weight: 45, ac: '14 + Dex (max 2)', stealthDisadv: true,
    description: 'Coat and leggings of overlapping scales. Medium armor. AC 14 + Dex (max +2). Stealth Disadvantage. Don 5 min / doff 1 min.',
    source: 'PHB 2024 p.216' },
  { id: 'breastplate', name: 'Breastplate', category: 'armor', subcategory: 'medium_armor',
    cost: '400 gp', weight: 20, ac: '14 + Dex (max 2)', stealthDisadv: false,
    description: 'Fitted metal chest plate over leather. Medium armor. AC 14 + Dex (max +2). Don 5 min / doff 1 min.',
    source: 'PHB 2024 p.216' },
  { id: 'half_plate', name: 'Half Plate Armor', category: 'armor', subcategory: 'medium_armor',
    cost: '750 gp', weight: 40, ac: '15 + Dex (max 2)', stealthDisadv: true,
    description: 'Shaped metal plates covering most of the body. Medium armor. AC 15 + Dex (max +2). Stealth Disadvantage. Don 5 min / doff 1 min.',
    source: 'PHB 2024 p.216' },

  // =================================================================
  // HEAVY ARMOR
  // =================================================================
  { id: 'ring_mail', name: 'Ring Mail', category: 'armor', subcategory: 'heavy_armor',
    cost: '30 gp', weight: 40, ac: '14', stealthDisadv: true,
    description: 'Leather reinforced with heavy rings. Heavy armor. AC 14 (no Dex). Stealth Disadvantage. Don 10 min / doff 5 min.',
    source: 'PHB 2024 p.216' },
  { id: 'chain_mail', name: 'Chain Mail', category: 'armor', subcategory: 'heavy_armor',
    cost: '75 gp', weight: 55, ac: '16', stealthDisadv: true, strReq: 13,
    description: 'Interlocking metal rings. Heavy armor. AC 16 (no Dex). Requires STR 13 (or speed reduced by 10 ft). Stealth Disadvantage. Don 10 min / doff 5 min.',
    source: 'PHB 2024 p.216' },
  { id: 'splint', name: 'Splint Armor', category: 'armor', subcategory: 'heavy_armor',
    cost: '200 gp', weight: 60, ac: '17', stealthDisadv: true, strReq: 15,
    description: 'Narrow vertical strips of metal riveted to a leather backing. Heavy armor. AC 17 (no Dex). Requires STR 15. Stealth Disadvantage. Don 10 min / doff 5 min.',
    source: 'PHB 2024 p.216' },
  { id: 'plate', name: 'Plate Armor', category: 'armor', subcategory: 'heavy_armor',
    cost: '1,500 gp', weight: 65, ac: '18', stealthDisadv: true, strReq: 15,
    description: 'Shaped, interlocking metal plates covering the entire body. Heavy armor. AC 18 (no Dex). Requires STR 15. Stealth Disadvantage. Don 10 min / doff 5 min.',
    source: 'PHB 2024 p.216' },
  { id: 'shield', name: 'Shield', category: 'armor', subcategory: 'shield',
    cost: '10 gp', weight: 6, ac: '+2', stealthDisadv: false,
    description: 'A wooden or metal shield strapped to one arm. Grants +2 AC. Can be donned or doffed as an action. You can benefit from only one shield at a time.',
    source: 'PHB 2024 p.216' },

  // =================================================================
  // ADVENTURING GEAR
  // =================================================================
  { id: 'backpack', name: 'Backpack', category: 'gear', subcategory: 'container',
    cost: '2 gp', weight: 5,
    description: 'A sturdy leather pack with straps. Holds up to 30 lbs. of gear.',
    source: 'PHB 2024 p.222' },
  { id: 'bedroll', name: 'Bedroll', category: 'gear', subcategory: 'camping',
    cost: '1 gp', weight: 7,
    description: 'A rolled sleeping mat. Necessary for a proper rest outdoors.',
    source: 'PHB 2024 p.222' },
  { id: 'blanket', name: 'Blanket', category: 'gear', subcategory: 'camping',
    cost: '5 sp', weight: 3,
    description: 'A woollen blanket. Keeps the cold at bay.',
    source: 'PHB 2024 p.222' },
  { id: 'rope_hempen_50', name: 'Rope, Hempen (50 ft)', category: 'gear', subcategory: 'utility',
    cost: '1 gp', weight: 10,
    description: '50 feet of hempen rope. 2 HP. Bursts if 5+ slashing damage in one hit.',
    source: 'PHB 2024 p.222' },
  { id: 'rope_silk_50', name: 'Rope, Silk (50 ft)', category: 'gear', subcategory: 'utility',
    cost: '10 gp', weight: 5,
    description: '50 feet of silk rope. 2 HP. Lighter, stronger, more expensive than hempen.',
    source: 'PHB 2024 p.222' },
  { id: 'torch', name: 'Torch', category: 'gear', subcategory: 'light',
    cost: '1 cp', weight: 1,
    description: 'A wooden torch. Burns for 1 hour, providing bright light in a 20-ft. radius and dim light out to 40 ft. A torch used as an improvised melee weapon deals 1 fire damage on a hit.',
    source: 'PHB 2024 p.222' },
  { id: 'tinderbox', name: 'Tinderbox', category: 'gear', subcategory: 'utility',
    cost: '5 sp', weight: 1,
    description: 'Flint, steel, and tinder. Lighting a torch takes an action; anything else takes at least 1 minute.',
    source: 'PHB 2024 p.222' },
  { id: 'waterskin', name: 'Waterskin', category: 'gear', subcategory: 'consumable',
    cost: '2 sp', weight: 5,
    description: 'A leather waterskin. Holds up to 4 pints of liquid. Weight given assumes full.',
    source: 'PHB 2024 p.222' },
  { id: 'rations_1_day', name: 'Rations (1 day)', category: 'gear', subcategory: 'food',
    cost: '5 sp', weight: 2,
    description: 'Dry food suitable for extended travel — jerky, dried fruit, hardtack. One day\'s worth of nutrition.',
    source: 'PHB 2024 p.222' },
  { id: 'mess_kit', name: 'Mess Kit', category: 'gear', subcategory: 'camping',
    cost: '2 sp', weight: 1,
    description: 'A tin box with a cup and simple cutlery. The box clamps together and can be used as a cooking pan.',
    source: 'PHB 2024 p.222' },
  { id: 'lantern_hooded', name: 'Lantern, Hooded', category: 'gear', subcategory: 'light',
    cost: '5 gp', weight: 2,
    description: 'Casts bright light in a 30-ft. radius and dim light for another 30 ft. Burns 1 flask of oil in 6 hours. A shutter action reduces to a 5-ft. dim light radius.',
    source: 'PHB 2024 p.222' },
  { id: 'oil_flask', name: 'Oil (flask)', category: 'gear', subcategory: 'consumable',
    cost: '1 sp', weight: 1,
    description: 'Fuels a lamp or lantern. Can be thrown up to 20 ft. as an improvised weapon; on hit, target coated. A fire source ignites for 5 fire damage. Can be poured over a 5-ft. square; ignition deals 5 fire damage to a creature entering the square first time per turn.',
    source: 'PHB 2024 p.222' },
  { id: 'crowbar', name: 'Crowbar', category: 'gear', subcategory: 'utility',
    cost: '2 gp', weight: 5,
    description: 'Grants Advantage on STR checks where leverage helps.',
    source: 'PHB 2024 p.222' },
  { id: 'grappling_hook', name: 'Grappling Hook', category: 'gear', subcategory: 'utility',
    cost: '2 gp', weight: 4,
    description: 'A four-tined iron hook. Tie to a rope to climb, secure, or hook objects.',
    source: 'PHB 2024 p.222' },
  { id: 'hammer', name: 'Hammer', category: 'gear', subcategory: 'utility',
    cost: '1 gp', weight: 3,
    description: 'A carpenter\'s hammer. Useful for driving pitons.',
    source: 'PHB 2024 p.222' },
  { id: 'piton', name: 'Piton', category: 'gear', subcategory: 'utility',
    cost: '5 cp', weight: 0.25,
    description: 'An iron spike. Drive into surfaces to anchor a rope. Usually sold in bundles.',
    source: 'PHB 2024 p.222' },
  { id: 'chalk_1', name: 'Chalk (1 piece)', category: 'gear', subcategory: 'utility',
    cost: '1 cp', weight: 0,
    description: 'A piece of writing chalk.',
    source: 'PHB 2024 p.222' },
  { id: 'candle', name: 'Candle', category: 'gear', subcategory: 'light',
    cost: '1 cp', weight: 0,
    description: 'Bright light in a 5-ft. radius, dim light for another 5 ft. Burns for 1 hour.',
    source: 'PHB 2024 p.222' },
  { id: 'ink_bottle', name: 'Ink (1 oz bottle)', category: 'gear', subcategory: 'writing',
    cost: '10 gp', weight: 0,
    description: 'A small bottle of ink. Suitable for writing or scribing.',
    source: 'PHB 2024 p.222' },
  { id: 'ink_pen', name: 'Ink Pen', category: 'gear', subcategory: 'writing',
    cost: '2 cp', weight: 0,
    description: 'A quill pen.',
    source: 'PHB 2024 p.222' },
  { id: 'paper_sheet', name: 'Paper (1 sheet)', category: 'gear', subcategory: 'writing',
    cost: '2 sp', weight: 0,
    description: 'A single sheet of paper.',
    source: 'PHB 2024 p.222' },
  { id: 'parchment_sheet', name: 'Parchment (1 sheet)', category: 'gear', subcategory: 'writing',
    cost: '1 sp', weight: 0,
    description: 'A single sheet of parchment.',
    source: 'PHB 2024 p.222' },
  { id: 'book', name: 'Book', category: 'gear', subcategory: 'writing',
    cost: '25 gp', weight: 5,
    description: 'A book of prose, poetry, notes, or record. Blank books used for personal journals are cheaper.',
    source: 'PHB 2024 p.222' },
  { id: 'component_pouch', name: 'Component Pouch', category: 'gear', subcategory: 'spellcasting',
    cost: '25 gp', weight: 2,
    description: 'A small pouch containing components for casting spells with material components (that don\'t specify a cost).',
    source: 'PHB 2024 p.222' },
  { id: 'spellbook', name: 'Spellbook', category: 'gear', subcategory: 'spellcasting',
    cost: '50 gp', weight: 3,
    description: 'A leather-bound tome with 100 blank vellum pages. Wizards scribe their spells here. Costs 50 gp new; replacing a lost spellbook costs 50 gp plus material costs to re-scribe spells.',
    source: 'PHB 2024 p.222' },
  { id: 'holy_symbol_amulet', name: 'Holy Symbol (Amulet)', category: 'gear', subcategory: 'spellcasting',
    cost: '5 gp', weight: 1,
    description: 'A symbol of a deity worn as a pendant. Used as a spellcasting focus for clerics and paladins. Can also be presented to Turn Undead.',
    source: 'PHB 2024 p.222' },
  { id: 'manacles', name: 'Manacles', category: 'gear', subcategory: 'utility',
    cost: '2 gp', weight: 6,
    description: 'Iron shackles that can restrain a Small or Medium creature. Escape requires a DC 20 Dexterity (Sleight of Hand) check or breaking (AC 19, 15 HP).',
    source: 'PHB 2024 p.222' },
  { id: 'ball_bearings', name: 'Ball Bearings (bag of 1,000)', category: 'gear', subcategory: 'utility',
    cost: '1 gp', weight: 2,
    description: 'Spill onto the ground: the bearings cover a 10-ft. square. A creature moving through must make DC 10 Dex save or fall Prone.',
    source: 'PHB 2024 p.222' },
  { id: 'caltrops', name: 'Caltrops (bag of 20)', category: 'gear', subcategory: 'utility',
    cost: '1 gp', weight: 2,
    description: 'Scatter to cover a 5-ft. square. Any creature moving into the area must succeed on a DC 15 Dex save or take 1 piercing damage, have their walking speed reduced to 0 until start of their next turn.',
    source: 'PHB 2024 p.222' },
  { id: 'bell', name: 'Bell', category: 'gear', subcategory: 'utility',
    cost: '1 gp', weight: 0,
    description: 'A small handbell.',
    source: 'PHB 2024 p.222' },

  // =================================================================
  // CONSUMABLES
  // =================================================================
  { id: 'potion_healing', name: 'Potion of Healing', category: 'consumable', subcategory: 'potion',
    cost: '50 gp', weight: 0.5,
    description: 'Regain 2d4 + 2 HP as an action or bonus action. Uncommon magic item.',
    source: 'DMG 2024 · common potion' },
  { id: 'potion_healing_greater', name: 'Potion of Greater Healing', category: 'consumable', subcategory: 'potion',
    cost: '200 gp', weight: 0.5,
    description: 'Regain 4d4 + 4 HP as an action or bonus action.',
    source: 'DMG 2024 · uncommon' },
  { id: 'potion_healing_superior', name: 'Potion of Superior Healing', category: 'consumable', subcategory: 'potion',
    cost: '1,000 gp', weight: 0.5,
    description: 'Regain 8d4 + 8 HP as an action or bonus action.',
    source: 'DMG 2024 · rare' },
  { id: 'potion_healing_supreme', name: 'Potion of Supreme Healing', category: 'consumable', subcategory: 'potion',
    cost: '10,000 gp', weight: 0.5,
    description: 'Regain 10d4 + 20 HP as an action or bonus action.',
    source: 'DMG 2024 · very rare' },
  { id: 'healers_kit', name: 'Healer\'s Kit', category: 'consumable', subcategory: 'kit',
    cost: '5 gp', weight: 3,
    description: 'Bandages, salves, splints. 10 uses. As an action, expend one use to stabilize a creature with 0 HP without needing to make a Wisdom (Medicine) check.',
    source: 'PHB 2024 p.222' },
  { id: 'alchemists_fire', name: 'Alchemist\'s Fire (flask)', category: 'consumable', subcategory: 'alchemy',
    cost: '50 gp', weight: 1,
    description: 'Thrown weapon (range 20 ft.). On hit, target takes 1d4 fire damage at the start of each of its turns. A creature can end this by using an action to make a DC 10 Dex check to extinguish the flames.',
    source: 'PHB 2024 p.222' },
  { id: 'acid_flask', name: 'Acid (flask)', category: 'consumable', subcategory: 'alchemy',
    cost: '25 gp', weight: 1,
    description: 'Thrown as an improvised weapon (range 20 ft.). On hit, target takes 2d6 acid damage.',
    source: 'PHB 2024 p.222' },
  { id: 'antitoxin', name: 'Antitoxin (vial)', category: 'consumable', subcategory: 'alchemy',
    cost: '50 gp', weight: 0,
    description: 'A creature that drinks the vial gains Advantage on saving throws against Poison for 1 hour. Confers no benefit to Undead or Constructs.',
    source: 'PHB 2024 p.222' },

  // =================================================================
  // MAGIC ITEMS (curated — party-relevant + common)
  // =================================================================
  { id: 'bag_of_holding', name: 'Bag of Holding', category: 'magic', subcategory: 'wondrous',
    cost: '500 gp (rare)', weight: 15, attunement: false,
    description: 'This bag has an interior space considerably larger than its outside dimensions: roughly 2 ft. in diameter at the mouth and 4 ft. deep. The bag can hold up to 500 lbs., not exceeding a volume of 64 cubic feet. Its weight is always 15 lbs. regardless of contents. Retrieving an item requires an action. Placing the bag inside an extradimensional space (Bag of Holding, Portable Hole, Handy Haversack) instantly destroys both items and opens a gate to the Astral Plane in the location.',
    source: 'DMG 2024 · uncommon' },
  { id: 'robe_of_bones', name: 'Robe of Bones', category: 'magic', subcategory: 'wondrous',
    cost: '5,000 gp (rare)', weight: 3, attunement: true, attunementRestriction: 'Wizard or Warlock',
    description: 'While attuned and wearing this robe, you can use an action to detach one of the twelve embroidered black bone patches and throw it up to 30 ft. The patch becomes an undead creature: 6 Skeletons or Zombies, 3 Ghouls, 2 Specters, or 1 Wight (once each, then that patch is gone). The undead act on their own initiative and obey your verbal commands. Detached patches regrow after a long rest — but only if the robe still bears the pattern.',
    source: 'DMG 2024 · rare (requires attunement by Wizard/Warlock)' },
  { id: 'cloak_of_elvenkind', name: 'Cloak of Elvenkind', category: 'magic', subcategory: 'wondrous',
    cost: '500 gp (uncommon)', weight: 1, attunement: true,
    description: 'While you wear this cloak with the hood up, Wisdom (Perception) checks made to see you have Disadvantage, and you have Advantage on Dexterity (Stealth) checks made to hide, as the cloak\'s color shifts to camouflage you. Pulling the hood up or down is a bonus action.',
    source: 'DMG 2024 · uncommon' },
  { id: 'boots_of_elvenkind', name: 'Boots of Elvenkind', category: 'magic', subcategory: 'wondrous',
    cost: '500 gp (uncommon)', weight: 1, attunement: false,
    description: 'While you wear these boots, your steps make no sound, regardless of the surface. You also have Advantage on Dexterity (Stealth) checks that rely on moving silently.',
    source: 'DMG 2024 · uncommon' },
  { id: 'ring_of_protection', name: 'Ring of Protection', category: 'magic', subcategory: 'ring',
    cost: '3,500 gp (rare)', weight: 0, attunement: true,
    description: 'You have a +1 bonus to AC and Saving Throws while wearing this ring.',
    source: 'DMG 2024 · rare' },
  { id: 'wand_of_magic_missiles', name: 'Wand of Magic Missiles', category: 'magic', subcategory: 'wand',
    cost: '500 gp (uncommon)', weight: 1, attunement: false,
    description: '7 charges. While holding it, you can expend 1 or more charges as an action to cast Magic Missile (1 charge = 1st-level cast; each extra charge adds a level up to 5th). Regains 1d6 + 1 expended charges at dawn. If you expend the last charge, roll a d20 — on a 1, the wand crumbles to ash.',
    source: 'DMG 2024 · uncommon' },
  { id: 'immovable_rod', name: 'Immovable Rod', category: 'magic', subcategory: 'wondrous',
    cost: '5,000 gp (uncommon)', weight: 2, attunement: false,
    description: 'This flat iron rod has a button on one end. Press the button (as an action) and the rod becomes magically fixed in place. Until you or another creature presses the button again, the rod doesn\'t move, even in defiance of gravity. Can hold up to 8,000 lbs.; if more weight is exceeded, it deactivates. A DC 30 Strength check can move it up to 10 ft. as an action.',
    source: 'DMG 2024 · uncommon' },
  { id: 'rope_of_climbing', name: 'Rope of Climbing', category: 'magic', subcategory: 'wondrous',
    cost: '2,000 gp (uncommon)', weight: 3, attunement: false,
    description: 'A 60-foot silk rope weighing 3 lbs. Can hold up to 3,000 lbs. On command (action; one end of the rope must be held), the rope animates: extends, coils, knots, ties, unties. Command word is spoken while holding it. Can be damaged (AC 20, 20 HP; regains 1 HP every 5 min if it has at least 1 HP).',
    source: 'DMG 2024 · uncommon' },

  // =================================================================
  // CAMPAIGN-SPECIFIC (custom to The Wayward Company)
  // =================================================================
  { id: 'sylas_necklace', name: 'The Necklace (Sylas\'s Spirit Jar)', category: 'magic', subcategory: 'campaign',
    cost: 'priceless', weight: 0, attunement: true, attunementRestriction: 'Sylas',
    description: 'A silver necklace with a small vessel-shaped pendant. Sylas has worn it since childhood. As of his taking the Lich Initiate feat, this necklace is his phylactery / spirit jar. Vaeloran has been studying it during their "spell study sessions" without Sylas realising. The necklace is what Vaeloran actually wants.',
    source: 'Campaign artifact — DM notes' },
  { id: 'coin_cipher_chest', name: 'The Coin Cipher Chest (sealed, in Sylas\'s Bag of Holding)', category: 'magic', subcategory: 'campaign',
    cost: 'unknown', weight: 0, attunement: false,
    description: 'An iron-bound chest bearing the Coin Cipher eclipse seal, hidden inside Sylas\'s Bag of Holding since the Vrass encounter (Session 5). Vrass believes he took it; the Coin Cipher does not yet know the party still has it. Contents undisclosed — see DM notes.',
    source: 'Campaign artifact — DM notes' }

];

// =====================================================================
// AUTO-GENERATED: MAGIC WEAPONS +1 / +2 / +3
// For every base weapon above, we synthesise three magic variants.
// Damage strings get the bonus added; rarity scales with the bonus.
// Add a new base weapon → three variants come along automatically.
// =====================================================================
(function generateMagicWeaponVariants() {
  const baseWeapons = ITEMS_2024.filter(function(it) { return it.category === 'weapon'; });
  const rarities = { 1: 'uncommon', 2: 'rare', 3: 'very rare' };
  baseWeapons.forEach(function(w) {
    [1, 2, 3].forEach(function(plus) {
      // Damage string: turn "1d8 slashing" into "1d8+1 slashing", or "1 piercing" into "2 piercing"
      let magicDamage = w.damage;
      const diceMatch = w.damage.match(/^(\d+d\d+)(\s+.*)$/);
      const flatMatch = w.damage.match(/^(\d+)(\s+.*)$/);
      if (diceMatch) {
        magicDamage = diceMatch[1] + '+' + plus + diceMatch[2];
      } else if (flatMatch) {
        magicDamage = (parseInt(flatMatch[1], 10) + plus) + flatMatch[2];
      }
      ITEMS_2024.push({
        id: w.id + '_plus' + plus,
        name: w.name + ' +' + plus,
        category: 'magic',
        subcategory: 'magic_weapon',
        cost: '(magic weapon · ' + rarities[plus] + ')',
        weight: w.weight,
        damage: magicDamage,
        properties: w.properties,
        mastery: w.mastery,
        attunement: false,
        description: 'You have a +' + plus + ' bonus to attack and damage rolls made with this magic weapon. In every other respect it behaves as a normal ' + w.name.toLowerCase() + '. Base damage becomes ' + magicDamage + '. Original properties: ' + ((w.properties || []).join(', ') || 'none') + '. Weapon Mastery (if you have proficiency): ' + (w.mastery || '—') + '.',
        source: 'DMG 2024 · ' + rarities[plus] + ' magic weapon'
      });
    });
  });
})();

// =====================================================================
// NAMED MAGIC WEAPONS (curated iconic set)
// Add more here on demand.
// =====================================================================
[
  { id: 'flame_tongue_longsword', name: 'Flame Tongue (Longsword)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 3, damage: '1d8 slashing + 2d6 fire', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'You can speak the sword\'s Command Word as a Bonus Action to make bright red flames erupt from the blade. Flames shed Bright Light in a 40-foot radius and Dim Light for an additional 40 feet. While the sword is ablaze, it deals an extra 2d6 Fire damage on a hit. Flames last until you use another Bonus Action to end them or drop or sheathe the sword. Available as any sword or greataxe — this entry is the longsword variant.',
    source: 'DMG 2024 · rare (requires attunement)' },
  { id: 'flame_tongue_greatsword', name: 'Flame Tongue (Greatsword)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 6, damage: '2d6 slashing + 2d6 fire', properties: ['Heavy', 'Two-Handed'],
    attunement: true,
    description: 'As Flame Tongue (Longsword) but built on a greatsword base.',
    source: 'DMG 2024 · rare (requires attunement)' },
  { id: 'frost_brand', name: 'Frost Brand', category: 'magic', subcategory: 'magic_weapon',
    cost: '(very rare)', weight: 3, damage: '1d8 slashing + 1d6 cold', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'When you hit with an attack using this sword, the target takes an extra 1d6 Cold damage. You have Resistance to Fire damage while you hold this sword. In addition, while you hold the sword, you can use an action to extinguish all nonmagical flames within 30 feet. The sword sheds Bright Light in a 10-foot radius and Dim Light for an additional 10 feet when the temperature around it is 0°F or colder.',
    source: 'DMG 2024 · very rare (requires attunement)' },
  { id: 'sun_blade', name: 'Sun Blade', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 3, damage: '1d8 radiant', properties: ['Finesse', 'Versatile (1d10)'],
    attunement: true,
    description: 'This item appears to be a longsword hilt. While grasping it, you can use a Bonus Action to cause a blade of pure radiance to spring into existence, or make the blade disappear. While the blade exists, this magic longsword has the Finesse property. You are proficient with it if you are proficient with any longsword or shortsword. The blade sheds Bright Light in a 15-foot radius and Dim Light for an additional 15 feet. The blade is a magic weapon that deals 1d8 Radiant damage (1d10 if wielded with two hands). On a hit, an Undead target takes an extra 1d8 Radiant damage. The Bright Light is Sunlight.',
    source: 'DMG 2024 · rare (requires attunement)' },
  { id: 'holy_avenger', name: 'Holy Avenger', category: 'magic', subcategory: 'magic_weapon',
    cost: '(legendary)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true, attunementRestriction: 'Paladin',
    description: 'You gain a +3 bonus to attack and damage rolls made with this magic sword. When you hit a Fiend or Undead with it, that creature takes an extra 2d10 Radiant damage. While you hold the sword drawn, it creates an aura in a 10-foot Emanation originating from you. You and all creatures friendly to you in the aura have Advantage on saves against spells and other magical effects. If you have 17+ levels of Paladin, the aura extends to 30 feet.',
    source: 'DMG 2024 · legendary (requires attunement by Paladin)' },
  { id: 'vorpal_sword', name: 'Vorpal Sword', category: 'magic', subcategory: 'magic_weapon',
    cost: '(legendary)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'You gain a +3 bonus to attack and damage rolls made with this magic weapon. In addition, the weapon ignores Resistance to slashing damage. When you attack a creature that has at least one head with this weapon and roll a 20 on the attack roll, you cut off one of the creature\'s heads. The creature dies if it cannot survive without the lost head. A creature is immune to this effect if it has Legendary Resistance or if the DM decides its head is too large to cut off.',
    source: 'DMG 2024 · legendary (requires attunement)' },
  { id: 'sword_of_sharpness', name: 'Sword of Sharpness', category: 'magic', subcategory: 'magic_weapon',
    cost: '(very rare)', weight: 3, damage: '1d8 slashing (see text)', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'When you attack an object with this magic sword and hit, maximise your weapon damage dice against the target. When you attack a creature with this weapon and roll a 20 on the attack roll, the target takes an extra 4d6 Slashing damage. Then roll another d20 — on 20 you lop off one of the target\'s limbs (DM chooses which; if all limbs are gone, chops off head).',
    source: 'DMG 2024 · very rare (requires attunement)' },
  { id: 'dragon_slayer_longsword', name: 'Dragon Slayer (Longsword)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: false,
    description: 'You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a Dragon with this weapon, the Dragon takes an extra 3d6 damage of the weapon\'s damage type. For this purpose, "Dragon" refers to any creature with the Dragon type, including Dragon Turtles and Wyverns.',
    source: 'DMG 2024 · rare' },
  { id: 'giant_slayer_longsword', name: 'Giant Slayer (Longsword)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: false,
    description: 'You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a Giant with this weapon, the Giant takes an extra 2d6 damage of the weapon\'s damage type and must succeed on a DC 15 Strength save or fall Prone. For this purpose, "Giant" refers to any creature with the Giant type, including Ettins and Trolls.',
    source: 'DMG 2024 · rare' },
  { id: 'berserker_axe', name: 'Berserker Axe', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 4, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'You gain a +1 bonus to attack and damage rolls made with this magic weapon. In addition, while you are attuned to this weapon, your HP max increases by 1 for each of your levels. Curse: while attuned, you have Disadvantage on attack rolls made with weapons other than this axe unless no foe is within 60 feet of you that you can see or hear. When a creature causes damage to you, you can\'t willingly part with the axe until you finish a Short Rest, having a compulsion to keep the axe within reach.',
    source: 'DMG 2024 · rare (requires attunement; cursed)' },
  { id: 'defender_longsword', name: 'Defender (Longsword)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(legendary)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'You gain a +3 bonus to attack and damage rolls made with this magic weapon. The first time you attack with the sword each of your turns, you can transfer some or all of the sword\'s bonus to your AC instead of using it on attacks. For example, you could reduce the bonus to your attack and damage by 2 to gain a +2 bonus to AC. The adjusted bonuses remain in effect until start of your next turn (until you release the weapon if you release it before then).',
    source: 'DMG 2024 · legendary (requires attunement)' },
  { id: 'dwarven_thrower', name: 'Dwarven Thrower (Warhammer)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(very rare)', weight: 2, damage: '1d8 bludgeoning', properties: ['Versatile (1d10)', 'Thrown (20/60)'],
    attunement: true, attunementRestriction: 'Dwarf',
    description: 'You gain a +3 bonus to attack and damage rolls made with this magic weapon. It has the Thrown property with a normal range of 20 feet and a long range of 60 feet. When you hit with a ranged attack using this weapon, it deals an extra 1d8 damage or, if the target is a Giant, 2d8 damage. Immediately after the attack, the weapon flies back to your hand.',
    source: 'DMG 2024 · very rare (requires attunement by Dwarf)' },
  { id: 'hammer_of_thunderbolts', name: 'Hammer of Thunderbolts (Maul)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(legendary)', weight: 15, damage: '2d6 bludgeoning', properties: ['Heavy', 'Two-Handed'],
    attunement: true,
    description: 'You gain a +1 bonus to attack and damage rolls made with this magic weapon. This bonus increases to +3 and grants special properties while you are wearing a Belt of Giant Strength and Gauntlets of Ogre Power. Giant\'s Bane: while attuned to all three items, when you hit a Giant with the hammer, the Giant takes an extra 1d8 damage and must succeed on a DC 17 CON save or die. Throwing the hammer produces a thunderclap; on a hit, you can expend up to 5 Charges to unleash devastating thunder (1 charge/hit = extra 2d6 Thunder + 300-ft thunder audible).',
    source: 'DMG 2024 · legendary (requires attunement)' },
  { id: 'luck_blade', name: 'Luck Blade', category: 'magic', subcategory: 'magic_weapon',
    cost: '(legendary)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'You gain a +1 bonus to attack and damage rolls made with this magic weapon. While the sword is on your person, you also gain a +1 bonus to saving throws. Luck: if the sword is on your person, you can call on its luck (no action required) to reroll one attack roll, ability check, or saving throw you dislike. Must use the second roll. Once used, cannot be used again until dawn. Wish (rare): the sword has 1d4 - 1 charges. While holding it, you can use an action to expend 1 charge to cast Wish. Property can\'t be used again until the next dawn.',
    source: 'DMG 2024 · legendary (requires attunement)' },
  { id: 'vicious_weapon', name: 'Vicious Weapon (Any)', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: null, damage: '(as base + 7)', properties: [],
    attunement: false,
    description: 'When you roll a 20 on an attack roll made with this weapon, the target takes an extra 7 damage of the weapon\'s type. Add this template to any weapon — replace "Any" with the base type when adding to inventory.',
    source: 'DMG 2024 · rare' },
  { id: 'sword_of_life_stealing', name: 'Sword of Life Stealing', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'When you attack a creature with this magic weapon and roll a 20 on the attack roll, the target takes an extra 3d6 Necrotic damage (provided the target is not a Construct or Undead). You gain temp HP equal to the extra damage dealt.',
    source: 'DMG 2024 · rare (requires attunement)' },
  { id: 'sword_of_wounding', name: 'Sword of Wounding', category: 'magic', subcategory: 'magic_weapon',
    cost: '(rare)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'Hit points lost to this weapon\'s damage can be regained only through a Short or Long Rest, rather than by regeneration, magic, or any other means. Once per turn when you hit a creature with the sword, you can wound the target. At the start of each of the wounded creature\'s turns, it takes 1d4 Necrotic damage for each time you\'ve wounded it, and it can then make a DC 15 CON save, ending the effect on itself on a success. Alternatively, the wounded creature or a creature within 5 ft. can use an action to make a DC 15 Wisdom (Medicine) check to end the effect.',
    source: 'DMG 2024 · rare (requires attunement)' },
  { id: 'nine_lives_stealer', name: 'Nine Lives Stealer', category: 'magic', subcategory: 'magic_weapon',
    cost: '(very rare)', weight: 3, damage: '1d8 slashing', properties: ['Versatile (1d10)'],
    attunement: true,
    description: 'You gain a +2 bonus to attack and damage rolls made with this magic weapon. The sword has 1d8 + 1 charges. When you attack a creature that has 100 HP or fewer with it and roll a 20 on the attack roll, that target must succeed on a DC 15 CON save or be slain instantly as the sword tears its life force from its body (creature is immune if it is a Construct or an Undead). The sword loses 1 charge if the creature is slain. When the sword has no charges, it loses this property.',
    source: 'DMG 2024 · very rare (requires attunement)' }
].forEach(function(it) { ITEMS_2024.push(it); });

// =====================================================================
// LOOKUPS (built AFTER magic-weapon auto-gen + named appends, so every
// item is indexed exactly once regardless of source.)
// =====================================================================
const ITEMS_BY_ID = ITEMS_2024.reduce(function(m, it) { m[it.id] = it; return m; }, {});

const ITEMS_BY_CATEGORY = ITEMS_2024.reduce(function(m, it) {
  if (!m[it.category]) m[it.category] = [];
  m[it.category].push(it);
  return m;
}, {});
