// =====================================================================
// THE WAYWARD COMPANY — 2024 PHB SPELL CATALOG
// ---------------------------------------------------------------------
// Wizard + Cleric class lists (core coverage through level 5, plus iconic
// higher-level entries). Add more on demand.
//
// Each entry:
//   id             — snake_case unique key
//   name           — display name
//   level          — 0 (cantrip) through 9
//   school         — abjuration | conjuration | divination | enchantment |
//                    evocation | illusion | necromancy | transmutation
//   classes        — array of class names this spell appears on
//   castingTime    — 'Action' | 'Bonus Action' | 'Reaction' | '1 minute' | etc.
//   range          — display string
//   components     — 'V, S, M (...)' etc.
//   duration       — display string
//   concentration  — bool (default false)
//   ritual         — bool (default false)
//   description    — full 2024 PHB text
//   atHigherLevels — verbatim upcast text, or null for cantrips / spells with no upcast
//   source         — PHB page ref
// =====================================================================

const SPELLS_2024 = [

  // =================================================================
  // CANTRIPS (level 0)
  // =================================================================
  { id: 'acid_splash', name: 'Acid Splash', level: 0, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You create an acidic bubble at a point within range, where it explodes in a 5-foot-radius Sphere. Each creature in that Sphere makes a Dexterity saving throw, taking 1d6 Acid damage on a failed save. This spell\'s damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).',
    atHigherLevels: null, source: 'PHB 2024 p.240' },
  { id: 'dancing_lights', name: 'Dancing Lights', level: 0, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'artificer'],
    castingTime: 'Action', range: '120 feet', components: 'V, S, M (a bit of phosphorus)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You create up to four torch-sized lights within range, each appearing as a hovering torch, lantern, or glowing orb. Each light sheds Dim Light in a 10-foot radius. As a Bonus Action, you can move the lights up to 60 feet each to a new spot within range.',
    atHigherLevels: null, source: 'PHB 2024 p.263' },
  { id: 'fire_bolt', name: 'Fire Bolt', level: 0, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '120 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 Fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried. Damage: 1d10 at level 1; 2d10 at 5; 3d10 at 11; 4d10 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.276' },
  { id: 'light', name: 'Light', level: 0, school: 'evocation', classes: ['wizard', 'cleric', 'sorcerer', 'bard'],
    castingTime: 'Action', range: 'Touch', components: 'V, M (a firefly or phosphorescent moss)', duration: '1 hour',
    description: 'You touch one object no larger than 10 feet in any dimension. Until the spell ends, the object sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet. Covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it (no action required).',
    atHigherLevels: null, source: 'PHB 2024 p.297' },
  { id: 'mage_hand', name: 'Mage Hand', level: 0, school: 'conjuration', classes: ['wizard', 'sorcerer', 'bard', 'warlock', 'artificer'],
    castingTime: 'Action', range: '30 feet', components: 'V, S', duration: '1 minute',
    description: 'A spectral, floating hand appears at a point within range. The hand lasts for the duration or until you dismiss it (no action required); it also disappears if you go more than 30 feet from it or cast this spell again. You can use your Bonus Action to control the hand, manipulating objects up to 10 lbs., opening unlocked containers, and so on.',
    atHigherLevels: null, source: 'PHB 2024 p.302' },
  { id: 'mending', name: 'Mending', level: 0, school: 'transmutation', classes: ['wizard', 'cleric', 'sorcerer', 'bard', 'druid', 'artificer'],
    castingTime: '1 minute', range: 'Touch', components: 'V, S, M (two lodestones)', duration: 'Instantaneous',
    description: 'This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace. This spell can physically repair a magic item or construct, but the spell can\'t restore magic to such an object.',
    atHigherLevels: null, source: 'PHB 2024 p.303' },
  { id: 'message', name: 'Message', level: 0, school: 'transmutation', classes: ['wizard', 'sorcerer', 'bard', 'artificer'],
    castingTime: 'Action', range: '120 feet', components: 'V, S, M (a copper wire)', duration: '1 round',
    description: 'You point at a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood blocks the spell.',
    atHigherLevels: null, source: 'PHB 2024 p.304' },
  { id: 'minor_illusion', name: 'Minor Illusion', level: 0, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: '30 feet', components: 'S, M (fleece)', duration: '1 minute',
    description: 'You create a sound or an image of an object within range that lasts for the duration. If you create a sound, its volume can range from a whisper to a scream. If you create an image of an object, it can be no larger than a 5-foot Cube. The illusion also ends if you dismiss it (no action required) or cast this spell again. A creature that uses its action to examine the illusion can determine that it is illusory with a successful Investigation check against your spell save DC.',
    atHigherLevels: null, source: 'PHB 2024 p.304' },
  { id: 'poison_spray', name: 'Poison Spray', level: 0, school: 'necromancy', classes: ['wizard', 'sorcerer', 'druid', 'warlock', 'artificer'],
    castingTime: 'Action', range: '30 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You extend your hand toward a creature within range and project a puff of noxious gas. The creature makes a Constitution saving throw, taking 1d12 Poison damage on a failed save. Damage: 1d12 at level 1; 2d12 at 5; 3d12 at 11; 4d12 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.311' },
  { id: 'prestidigitation', name: 'Prestidigitation', level: 0, school: 'transmutation', classes: ['wizard', 'sorcerer', 'bard', 'warlock', 'artificer'],
    castingTime: 'Action', range: '10 feet', components: 'V, S', duration: 'Up to 1 hour',
    description: 'This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following effects within range: (1) an instantaneous, harmless sensory effect (shower of sparks, gust of wind, faint musical notes, odd odor); (2) instantaneously light or snuff a candle, torch, or small campfire; (3) instantaneously clean or soil a Small object; (4) chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour; (5) make a color, small mark, or symbol appear on an object or surface for 1 hour; (6) create a Tiny nonmagical trinket or an illusory image that fits in your hand and lasts until end of your next turn.',
    atHigherLevels: null, source: 'PHB 2024 p.313' },
  { id: 'ray_of_frost', name: 'Ray of Frost', level: 0, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 Cold damage, and its Speed is reduced by 10 feet until start of your next turn. Damage: 1d8 at level 1; 2d8 at 5; 3d8 at 11; 4d8 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.315' },
  { id: 'shocking_grasp', name: 'Shocking Grasp', level: 0, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S', duration: 'Instantaneous',
    description: 'Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have Advantage on the attack if the target is wearing armor made of metal. On a hit, the target takes 1d8 Lightning damage, and it can\'t take Reactions until start of its next turn. Damage: 1d8 at level 1; 2d8 at 5; 3d8 at 11; 4d8 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.323' },
  { id: 'true_strike', name: 'True Strike', level: 0, school: 'divination', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: 'Self', components: 'S, M (a weapon with which you have proficiency and that is worth 1+ CP)', duration: 'Instantaneous',
    description: 'Guided by a flash of magical insight, you make one attack with the weapon used in the spell\'s casting. The attack uses your spellcasting ability for the attack and damage rolls instead of using STR or DEX. If the attack deals damage, it can be Radiant damage instead of the weapon\'s normal type. In addition, if the weapon has a Two-Handed or Versatile property, it deals its Two-Handed die on the hit. Damage bonus die when cast at higher levels: 1d6 at 5; 2d6 at 11; 3d6 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.334' },
  { id: 'chill_touch', name: 'Chill Touch', level: 0, school: 'necromancy', classes: ['wizard', 'sorcerer', 'warlock'],
    castingTime: 'Action', range: '120 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature. On a hit, the target takes 1d10 Necrotic damage, and it can\'t regain HP until the start of your next turn. Until then, the hand clings to the target. If you hit an Undead target, it also has Disadvantage on attack rolls against you until the end of your next turn. Damage: 1d10 at level 1; 2d10 at 5; 3d10 at 11; 4d10 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.257' },
  { id: 'friends', name: 'Friends', level: 0, school: 'enchantment', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: 'Self', components: 'S, M (traces of makeup)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'For the duration, you have Advantage on all Charisma checks directed at one creature of your choice that isn\'t hostile. When the spell ends, the creature realizes you used magic to influence its mood and becomes hostile toward you.',
    atHigherLevels: null, source: 'PHB 2024 p.279' },

  // Cleric cantrips
  { id: 'guidance', name: 'Guidance', level: 0, school: 'divination', classes: ['cleric', 'druid', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You touch one willing creature and choose a skill. Until the spell ends, the target can roll a d4 and add it to one ability check of its choice that uses the chosen skill. It can roll the die before or after making the check. The spell then ends.',
    atHigherLevels: null, source: 'PHB 2024 p.283' },
  { id: 'sacred_flame', name: 'Sacred Flame', level: 0, school: 'evocation', classes: ['cleric'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'Flame-like radiance descends on a creature that you can see within range. The target makes a Dexterity saving throw. On a failed save, it takes 1d8 Radiant damage. The target gains no benefit from Half or Three-Quarters Cover for this save. Damage: 1d8 at level 1; 2d8 at 5; 3d8 at 11; 4d8 at 17.',
    atHigherLevels: null, source: 'PHB 2024 p.318' },
  { id: 'spare_the_dying', name: 'Spare the Dying', level: 0, school: 'necromancy', classes: ['cleric', 'druid', 'artificer'],
    castingTime: 'Action', range: '15 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'Choose a creature within range that has 0 HP and isn\'t Dead. The creature becomes Stable. Stable creatures don\'t make Death Saving Throws even though they have 0 HP.',
    atHigherLevels: null, source: 'PHB 2024 p.326' },
  { id: 'thaumaturgy', name: 'Thaumaturgy', level: 0, school: 'transmutation', classes: ['cleric', 'sorcerer', 'bard'],
    castingTime: 'Action', range: '30 feet', components: 'V', duration: 'Up to 1 minute',
    description: 'You manifest a minor wonder, a sign of supernatural power, within range: voice booms up to 3× as loud, cause flames to flicker/brighten/dim/change color for 1 minute, cause harmless tremors in the ground for 1 minute, create an instantaneous sound (thunderclap to raven\'s call) that emanates from a point within range, cause an unlocked door or window to fly open or slam shut, alter the appearance of your eyes for 1 minute. Up to three effects active at once; dismiss as an action.',
    atHigherLevels: null, source: 'PHB 2024 p.333' },
  { id: 'toll_the_dead', name: 'Toll the Dead', level: 0, school: 'necromancy', classes: ['cleric', 'wizard', 'warlock'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target makes a Wisdom saving throw. On a failed save, it takes 1d8 Necrotic damage. If the target is missing any of its HP, it instead takes 1d12 Necrotic damage. Damage dice increase at levels 5, 11, and 17 (2d8/2d12, 3d8/3d12, 4d8/4d12).',
    atHigherLevels: null, source: 'PHB 2024 p.333' },

  // =================================================================
  // LEVEL 1 SPELLS
  // =================================================================
  { id: 'magic_missile', name: 'Magic Missile', level: 1, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '120 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 Force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
    atHigherLevels: 'Using a spell slot of level 2+: the spell creates one more dart for each slot level above 1st.',
    source: 'PHB 2024 p.301' },
  { id: 'shield', name: 'Shield', level: 1, school: 'abjuration', classes: ['wizard', 'sorcerer'],
    castingTime: 'Reaction, which you take when you are hit by an attack roll or targeted by the Magic Missile spell', range: 'Self', components: 'V, S', duration: '1 round',
    description: 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from Magic Missile.',
    atHigherLevels: null, source: 'PHB 2024 p.323' },
  { id: 'mage_armor', name: 'Mage Armor', level: 1, school: 'abjuration', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (a piece of cured leather)', duration: '8 hours',
    description: 'You touch a willing creature who isn\'t wearing armor. Until the spell ends, the target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor.',
    atHigherLevels: null, source: 'PHB 2024 p.302' },
  { id: 'detect_magic', name: 'Detect Magic', level: 1, school: 'divination', classes: ['wizard', 'cleric', 'druid', 'sorcerer', 'bard', 'paladin', 'ranger'],
    castingTime: 'Action or Ritual', range: 'Self', components: 'V, S', duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, you sense the presence of magical effects within 30 feet of yourself. If you sense such effects, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any. The spell is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
    atHigherLevels: null, source: 'PHB 2024 p.268' },
  { id: 'sleep', name: 'Sleep', level: 1, school: 'enchantment', classes: ['wizard', 'sorcerer', 'bard'],
    castingTime: 'Action', range: '90 feet', components: 'V, S, M (a pinch of fine sand, rose petals, or a cricket)', duration: '1 minute',
    description: 'Roll 5d8; the total is how many HP of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current HP (ignoring Unconscious creatures). Each creature affected by this spell falls Unconscious and has the Incapacitated condition until the spell ends. Damage or another creature using an action to shake or slap it awake ends the effect on it.',
    atHigherLevels: 'Using a spell slot of level 2+: roll an additional 2d8 for each slot level above 1st.',
    source: 'PHB 2024 p.325' },
  { id: 'burning_hands', name: 'Burning Hands', level: 1, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Self (15-foot Cone)', components: 'V, S', duration: 'Instantaneous',
    description: 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth. Each creature in a 15-foot Cone makes a Dexterity saving throw, taking 3d6 Fire damage on a failed save or half as much on a successful one. Flammable objects in the cone that aren\'t being worn or carried ignite.',
    atHigherLevels: 'Using a spell slot of level 2+: damage increases by 1d6 for each slot level above 1st.',
    source: 'PHB 2024 p.251' },
  { id: 'chromatic_orb', name: 'Chromatic Orb', level: 1, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '90 feet', components: 'V, S, M (a diamond worth 50+ GP)', duration: 'Instantaneous',
    description: 'You hurl a 4-inch sphere of energy at a creature you can see within range. Choose Acid, Cold, Fire, Lightning, Poison, or Thunder for the type of orb, then make a ranged spell attack against the target. On a hit, the target takes 3d8 damage of the chosen type. If you roll the same number on two or more dice, the orb leaps to a different creature of your choice within 60 feet of the target and makes a new attack.',
    atHigherLevels: 'Using a spell slot of level 2+: damage increases by 1d8 for each slot level above 1st.',
    source: 'PHB 2024 p.257' },
  { id: 'silent_image', name: 'Silent Image', level: 1, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (fleece)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot Cube. The image appears at a spot within range and lasts for the duration. It has no sound, smell, or other sensory effects. You can use your action to cause the image to move any spot within range. Physical interaction with the image reveals it to be an illusion, and an Investigation check against your spell save DC while examining it determines the illusion.',
    atHigherLevels: null, source: 'PHB 2024 p.323' },
  { id: 'disguise_self', name: 'Disguise Self', level: 1, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'artificer'],
    castingTime: 'Action', range: 'Self', components: 'V, S', duration: '1 hour',
    description: 'You make yourself — including your clothing, armor, weapons, and other belongings — look different until the spell ends or until you use your action to dismiss it. You can seem 1 foot shorter or taller, thinner, fatter, or in between. The changes wrought by this spell fail to hold up to physical inspection.',
    atHigherLevels: null, source: 'PHB 2024 p.269' },
  { id: 'find_familiar', name: 'Find Familiar', level: 1, school: 'conjuration', classes: ['wizard'],
    castingTime: '1 hour or Ritual', range: '10 feet', components: 'V, S, M (10 GP worth of charcoal, incense, and herbs — consumed)', duration: 'Instantaneous', ritual: true,
    description: 'You gain the service of a familiar, a spirit that takes an animal form you choose (Tiny beast with CR 0). Your familiar acts independently of you, but it always obeys your commands. In combat it rolls its own initiative and acts on its own turn. As an action, you can temporarily dismiss it or summon it back. When it drops to 0 HP, it disappears until you cast the spell again.',
    atHigherLevels: null, source: 'PHB 2024 p.273' },
  { id: 'unseen_servant', name: 'Unseen Servant', level: 1, school: 'conjuration', classes: ['wizard', 'bard', 'warlock'],
    castingTime: 'Action or Ritual', range: '60 feet', components: 'V, S, M (a piece of string and a bit of wood)', duration: '1 hour', ritual: true,
    description: 'This spell creates an invisible, mindless, shapeless Medium force that performs simple tasks at your command until the spell ends. The servant springs into existence in an unoccupied space on the ground within range. It has AC 10, 1 HP, and a Strength of 2. It can\'t attack. As a Bonus Action, you can command it to move up to 15 feet and interact with an object.',
    atHigherLevels: null, source: 'PHB 2024 p.335' },
  { id: 'false_life', name: 'False Life', level: 1, school: 'necromancy', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Self', components: 'V, S, M (a small amount of alcohol or distilled spirits)', duration: '1 hour',
    description: 'Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 Temporary Hit Points for the duration.',
    atHigherLevels: 'Using a spell slot of level 2+: Temporary HP increases by 5 for each slot level above 1st.',
    source: 'PHB 2024 p.272' },
  { id: 'ray_of_enfeeblement', name: 'Ray of Enfeeblement', level: 1, school: 'necromancy', classes: ['wizard', 'warlock'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'A black beam of enervating energy springs from your finger toward a creature within range. Make a ranged spell attack against the target. On a hit, it deals 2d6 Necrotic damage, and the target has Disadvantage on Strength-based attack rolls and Strength Ability Checks until the spell ends. On each subsequent turn, you can use your action to deal 2d6 Necrotic damage to the target automatically. At the end of each of its turns, the target can attempt a CON save to end the spell.',
    atHigherLevels: 'Using a spell slot of level 2+: initial damage increases by 1d6 for each slot level above 1st.',
    source: 'PHB 2024 p.315' },

  // Cleric level 1
  { id: 'bless', name: 'Bless', level: 1, school: 'enchantment', classes: ['cleric', 'paladin'],
    castingTime: 'Action', range: '30 feet', components: 'V, S, M (a sprinkling of holy water)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the result.',
    atHigherLevels: 'Using a spell slot of level 2+: you can target one additional creature for each slot level above 1st.',
    source: 'PHB 2024 p.249' },
  { id: 'cure_wounds', name: 'Cure Wounds', level: 1, school: 'abjuration', classes: ['cleric', 'druid', 'bard', 'paladin', 'ranger', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S', duration: 'Instantaneous',
    description: 'A creature you touch regains a number of HP equal to 2d8 + your spellcasting ability modifier. This spell has no effect on Constructs or Undead.',
    atHigherLevels: 'Using a spell slot of level 2+: healing increases by 2d8 for each slot level above 1st.',
    source: 'PHB 2024 p.263' },
  { id: 'guiding_bolt', name: 'Guiding Bolt', level: 1, school: 'evocation', classes: ['cleric'],
    castingTime: 'Action', range: '120 feet', components: 'V, S', duration: '1 round',
    description: 'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 Radiant damage, and the next attack roll made against this target before the end of your next turn has Advantage, thanks to the mystical dim light glittering on the target until then.',
    atHigherLevels: 'Using a spell slot of level 2+: damage increases by 1d6 for each slot level above 1st.',
    source: 'PHB 2024 p.283' },
  { id: 'healing_word', name: 'Healing Word', level: 1, school: 'abjuration', classes: ['cleric', 'druid', 'bard'],
    castingTime: 'Bonus Action', range: '60 feet', components: 'V', duration: 'Instantaneous',
    description: 'A creature of your choice that you can see within range regains HP equal to 2d4 + your spellcasting ability modifier. This spell has no effect on Constructs or Undead.',
    atHigherLevels: 'Using a spell slot of level 2+: healing increases by 1d4 for each slot level above 1st.',
    source: 'PHB 2024 p.290' },
  { id: 'inflict_wounds', name: 'Inflict Wounds', level: 1, school: 'necromancy', classes: ['cleric'],
    castingTime: 'Action', range: '30 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'Make a ranged spell attack against a creature within range. On a hit, the target takes 2d10 Necrotic damage.',
    atHigherLevels: 'Using a spell slot of level 2+: damage increases by 2d10 for each slot level above 1st.',
    source: 'PHB 2024 p.294' },
  { id: 'sanctuary', name: 'Sanctuary', level: 1, school: 'abjuration', classes: ['cleric', 'artificer'],
    castingTime: 'Bonus Action', range: '30 feet', components: 'V, S, M (a small silver mirror)', duration: '1 minute',
    description: 'You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn\'t protect the warded creature from area effects.',
    atHigherLevels: null, source: 'PHB 2024 p.319' },
  { id: 'shield_of_faith', name: 'Shield of Faith', level: 1, school: 'abjuration', classes: ['cleric', 'paladin'],
    castingTime: 'Bonus Action', range: '60 feet', components: 'V, S, M (a small parchment with a bit of holy text)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.',
    atHigherLevels: null, source: 'PHB 2024 p.323' },
  { id: 'bane', name: 'Bane', level: 1, school: 'enchantment', classes: ['cleric', 'bard'],
    castingTime: 'Action', range: '30 feet', components: 'V, S, M (a drop of blood)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this save makes an attack roll or a saving throw before the spell ends, the target must subtract 1d4 from the attack roll or saving throw.',
    atHigherLevels: 'Using a spell slot of level 2+: you can target one additional creature for each slot level above 1st.',
    source: 'PHB 2024 p.246' },

  // =================================================================
  // LEVEL 2 SPELLS
  // =================================================================
  { id: 'misty_step', name: 'Misty Step', level: 2, school: 'conjuration', classes: ['wizard', 'sorcerer', 'warlock'],
    castingTime: 'Bonus Action', range: 'Self', components: 'V', duration: 'Instantaneous',
    description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    atHigherLevels: null, source: 'PHB 2024 p.306' },
  { id: 'web', name: 'Web', level: 2, school: 'conjuration', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (a bit of spiderweb)', duration: 'Concentration, up to 1 hour', concentration: true,
    description: 'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot Cube from that point for the duration. The webs are Difficult Terrain and lightly obscure the area. If the webs aren\'t anchored between two solid surfaces, they collapse. Any creature that enters the webs or starts its turn there must succeed on a Dexterity saving throw or have the Restrained condition; a Restrained creature can use an action to make a Strength check to escape. Fire damage to the webs destroys them.',
    atHigherLevels: null, source: 'PHB 2024 p.337' },
  { id: 'invisibility', name: 'Invisibility', level: 2, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'warlock', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (an eyelash encased in gum arabic)', duration: 'Concentration, up to 1 hour', concentration: true,
    description: 'A creature you touch has the Invisible condition until the spell ends. It ends early on the target immediately after it makes an attack roll, deals damage, or casts a spell.',
    atHigherLevels: 'Using a spell slot of level 3+: you can target one additional creature for each slot level above 2nd.',
    source: 'PHB 2024 p.296' },
  { id: 'mirror_image', name: 'Mirror Image', level: 2, school: 'illusion', classes: ['wizard', 'sorcerer', 'warlock', 'bard'],
    castingTime: 'Action', range: 'Self', components: 'V, S', duration: '1 minute',
    description: 'Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions. Each time a creature targets you with an attack, roll a d6: 1-2 destroys no duplicate but the attack is against the duplicate closest to it; 3-4 or 5-6 tables in PHB determine outcomes. AC of duplicate = 10 + DEX modifier.',
    atHigherLevels: null, source: 'PHB 2024 p.304' },
  { id: 'suggestion', name: 'Suggestion', level: 2, school: 'enchantment', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: '30 feet', components: 'V, M (a snake\'s tongue and a bit of honeycomb or a drop of sweet oil)', duration: 'Concentration, up to 8 hours', concentration: true,
    description: 'You suggest a course of activity in 25 words or fewer and magically influence one creature you can see within range that can hear and understand you. The suggestion must sound achievable and reasonable. Wisdom saving throw negates. The target pursues the course of action you described to the best of its ability. The suggested course of action can continue for the duration.',
    atHigherLevels: null, source: 'PHB 2024 p.331' },
  { id: 'scorching_ray', name: 'Scorching Ray', level: 2, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '120 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 Fire damage.',
    atHigherLevels: 'Using a spell slot of level 3+: you create one additional ray for each slot level above 2nd.',
    source: 'PHB 2024 p.319' },
  { id: 'shatter', name: 'Shatter', level: 2, school: 'evocation', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (a chip of mica)', duration: 'Instantaneous',
    description: 'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius Sphere centered there makes a CON save, taking 3d8 Thunder damage on a failed save or half on a successful one. A creature made of inorganic material such as stone, crystal, or metal has Disadvantage on the save. A nonmagical object that isn\'t being worn or carried also takes the damage if it\'s in the spell\'s area.',
    atHigherLevels: 'Using a spell slot of level 3+: damage increases by 1d8 for each slot level above 2nd.',
    source: 'PHB 2024 p.322' },
  { id: 'phantasmal_force', name: 'Phantasmal Force', level: 2, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (a bit of fleece)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You craft an illusion in the mind of a creature within range. The target makes an Intelligence saving throw; on a failure, you place an illusion of an object, a creature, or some other visible phenomenon no larger than a 10-foot cube in the target\'s mind. The illusion appears to be real and moves within the range as you desire. If the illusion is a creature and directly attacks the target, the target takes 1d6 Psychic damage on each of its turns. The target rationalizes contradictions.',
    atHigherLevels: null, source: 'PHB 2024 p.310' },
  { id: 'darkness', name: 'Darkness', level: 2, school: 'evocation', classes: ['wizard', 'sorcerer', 'warlock'],
    castingTime: 'Action', range: '60 feet', components: 'V, M (a bit of fur wrapped in a scrap of dark cloth)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'Magical darkness spreads from a point you choose within range to fill a 15-foot-radius sphere for the duration. The darkness spreads around corners. A creature with Darkvision can\'t see through this darkness. Nonmagical light can\'t illuminate it. If the point you choose is on an object you are holding or one that isn\'t being worn or carried, the darkness emanates from the object and moves with it.',
    atHigherLevels: null, source: 'PHB 2024 p.267' },

  // Cleric level 2
  { id: 'spiritual_weapon', name: 'Spiritual Weapon', level: 2, school: 'evocation', classes: ['cleric'],
    castingTime: 'Bonus Action', range: '60 feet', components: 'V, S', duration: '1 minute',
    description: 'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes Force damage equal to 1d8 + your spellcasting ability modifier. As a Bonus Action on your subsequent turns, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.',
    atHigherLevels: 'Using a spell slot of level 3+: damage increases by 1d8 for every two slot levels above 2nd.',
    source: 'PHB 2024 p.328' },
  { id: 'silence', name: 'Silence', level: 2, school: 'illusion', classes: ['cleric', 'bard', 'ranger'],
    castingTime: 'Action or Ritual', range: '120 feet', components: 'V, S', duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, no sound can be created within or pass through a 20-foot-radius Sphere centered on a point you choose within range. Any creature or object entirely inside the Sphere has Immunity to Thunder damage, and creatures fully inside have the Deafened condition. Casting a spell that includes a verbal component is impossible there.',
    atHigherLevels: null, source: 'PHB 2024 p.323' },
  { id: 'hold_person', name: 'Hold Person', level: 2, school: 'enchantment', classes: ['cleric', 'wizard', 'sorcerer', 'bard', 'druid', 'warlock'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (a small, straight piece of iron)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'Choose a Humanoid that you can see within range. The target must succeed on a Wisdom saving throw or have the Paralyzed condition for the duration. At the end of each of its turns, the target can attempt another Wisdom save; on a success, the spell ends on it.',
    atHigherLevels: 'Using a spell slot of level 3+: you can target one additional Humanoid for each slot level above 2nd. The Humanoids must be within 30 feet of each other.',
    source: 'PHB 2024 p.291' },
  { id: 'lesser_restoration', name: 'Lesser Restoration', level: 2, school: 'abjuration', classes: ['cleric', 'druid', 'bard', 'paladin', 'ranger', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S', duration: 'Instantaneous',
    description: 'You touch a creature and can end one condition on it: Blinded, Deafened, Paralyzed, or Poisoned.',
    atHigherLevels: null, source: 'PHB 2024 p.296' },
  { id: 'aid', name: 'Aid', level: 2, school: 'abjuration', classes: ['cleric', 'paladin', 'artificer'],
    castingTime: 'Action', range: '30 feet', components: 'V, S, M (a strip of white cloth)', duration: '8 hours',
    description: 'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target\'s HP maximum and current HP increase by 5 for the duration.',
    atHigherLevels: 'Using a spell slot of level 3+: each target\'s HP increase by an additional 5 for each slot level above 2nd.',
    source: 'PHB 2024 p.242' },

  // =================================================================
  // LEVEL 3 SPELLS
  // =================================================================
  { id: 'fireball', name: 'Fireball', level: 3, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '150 feet', components: 'V, S, M (a ball of bat guano and sulfur)', duration: 'Instantaneous',
    description: 'A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into a fiery explosion. Each creature in a 20-foot-radius Sphere centered on that point makes a Dexterity saving throw, taking 8d6 Fire damage on a failed save or half as much on a successful one. Flammable objects in the area that aren\'t being worn or carried ignite.',
    atHigherLevels: 'Using a spell slot of level 4+: damage increases by 1d6 for each slot level above 3rd.',
    source: 'PHB 2024 p.278' },
  { id: 'counterspell', name: 'Counterspell', level: 3, school: 'abjuration', classes: ['wizard', 'sorcerer', 'warlock'],
    castingTime: 'Reaction, which you take when you see a creature within 60 feet of yourself casting a spell', range: '60 feet', components: 'S, M (a fragment of a recently cast spell)', duration: 'Instantaneous',
    description: 'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of level 3 or lower, its spell fails. If it is casting a spell of level 4+, make an ability check using your spellcasting ability (DC = 10 + the spell\'s level). On a success, the creature\'s spell fails.',
    atHigherLevels: 'Using a spell slot of level 4+: the interrupted spell has no effect if its level is less than or equal to the slot you used.',
    source: 'PHB 2024 p.260' },
  { id: 'fly', name: 'Fly', level: 3, school: 'transmutation', classes: ['wizard', 'sorcerer', 'warlock', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (a wing feather)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'You touch a willing creature. The target gains a Fly Speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can somehow stop the fall.',
    atHigherLevels: 'Using a spell slot of level 4+: you can target one additional creature for each slot level above 3rd.',
    source: 'PHB 2024 p.279' },
  { id: 'fireball_cleric_dawn', name: 'Daylight', level: 3, school: 'evocation', classes: ['cleric', 'druid', 'sorcerer', 'ranger'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: '1 hour',
    description: 'A 60-foot-radius Sphere of light spreads out from a point you choose within range. The sphere is Bright Light and sheds Dim Light for an additional 60 feet. If you chose a point on an object you are holding or one that isn\'t being worn or carried, the light shines from the object and moves with it. Completely covering the affected object with an opaque object, such as a bowl or a helm, blocks the light. If any of this spell\'s area overlaps with an area of Darkness created by a spell of level 3 or lower, the spell that created the Darkness is dispelled.',
    atHigherLevels: null, source: 'PHB 2024 p.267' },
  { id: 'dispel_magic', name: 'Dispel Magic', level: 3, school: 'abjuration', classes: ['wizard', 'cleric', 'sorcerer', 'bard', 'druid', 'paladin', 'warlock', 'artificer'],
    castingTime: 'Action', range: '120 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'Choose one creature, object, or magical effect within range. Any Spell of level 3 or lower on the target ends. For each spell of level 4+ on the target, make an ability check using your spellcasting ability (DC = 10 + the spell\'s level). On a success, the spell ends.',
    atHigherLevels: 'Using a spell slot of level 4+: you automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
    source: 'PHB 2024 p.269' },
  { id: 'fear', name: 'Fear', level: 3, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: 'Self (30-foot Cone)', components: 'V, S, M (a white feather or the heart of a hen)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You project a phantasmal image of a creature\'s worst fears. Each creature in a 30-foot Cone must succeed on a Wisdom saving throw or drop whatever it is holding and have the Frightened condition for the duration. While Frightened by this spell, a creature must take the Dash action and move away from you by the safest route on each of its turns, unless there is nowhere to move. If the creature ends its turn in a location where it doesn\'t have Line of Sight to you, the creature can make a Wisdom save, ending the effect on itself on a success.',
    atHigherLevels: null, source: 'PHB 2024 p.273' },
  { id: 'lightning_bolt', name: 'Lightning Bolt', level: 3, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Self (100-foot Line)', components: 'V, S, M (a bit of fur and a rod of amber, crystal, or glass)', duration: 'Instantaneous',
    description: 'A stroke of lightning forming a 100-foot-long, 5-foot-wide line blasts out from you in a direction you choose. Each creature in the line makes a Dexterity saving throw, taking 8d6 Lightning damage on a failed save or half as much on a successful one.',
    atHigherLevels: 'Using a spell slot of level 4+: damage increases by 1d6 for each slot level above 3rd.',
    source: 'PHB 2024 p.298' },
  { id: 'major_image', name: 'Major Image', level: 3, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: '120 feet', components: 'V, S, M (a bit of fleece)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'You create the image of an object, a creature, or some other visible phenomenon no larger than a 20-foot Cube. The image appears at a spot you can see within range and lasts for the duration. It seems completely real, including sounds, smells, and temperature appropriate to the thing depicted. You can\'t create sufficient heat or cold to cause damage. Physical interaction reveals the illusion, and an Investigation check reveals it.',
    atHigherLevels: 'Using a spell slot of level 6+: the spell lasts until dispelled without requiring your Concentration.',
    source: 'PHB 2024 p.302' },
  { id: 'hypnotic_pattern', name: 'Hypnotic Pattern', level: 3, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action', range: '120 feet', components: 'S, M (a glowing stick of incense or a crystal vial filled with phosphorescent material)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You create a twisting pattern of colors that weaves through the air inside a 30-foot Cube within range. The pattern appears for a moment and vanishes. Each creature in the Cube that can see the pattern must succeed on a Wisdom saving throw or have the Charmed condition for the duration. While Charmed by this spell, the creature has the Incapacitated condition and its Speed is 0. The spell ends for an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.',
    atHigherLevels: null, source: 'PHB 2024 p.293' },
  { id: 'animate_dead', name: 'Animate Dead', level: 3, school: 'necromancy', classes: ['wizard', 'cleric'],
    castingTime: '1 minute', range: '10 feet', components: 'V, S, M (a drop of blood, a piece of flesh, and a pinch of bone dust)', duration: 'Instantaneous',
    description: 'This spell creates an Undead servant. Choose a pile of bones or a corpse of a Small or Medium Humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an Undead creature. The target becomes a Skeleton if you chose bones or a Zombie if you chose a corpse (see stat blocks). On each of your turns, you can use a Bonus Action to command the Undead created by this spell if it is within 60 feet of you. You maintain control over a maximum of four Undead at any given time. Each time you cast the spell using a spell slot of 3rd level, you reassert control over up to four created Undead.',
    atHigherLevels: 'Using a spell slot of level 4+: you can animate or reassert control over two additional Undead for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.',
    source: 'PHB 2024 p.245' },

  // Cleric level 3
  { id: 'revivify', name: 'Revivify', level: 3, school: 'necromancy', classes: ['cleric', 'paladin', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (diamonds worth 300+ GP, which the spell consumes)', duration: 'Instantaneous',
    description: 'You touch a creature that has died within the last minute. That creature returns to life with 1 HP. This spell can\'t return to life a creature that has died of old age, nor can it restore any missing body parts.',
    atHigherLevels: null, source: 'PHB 2024 p.316' },
  { id: 'spirit_guardians', name: 'Spirit Guardians', level: 3, school: 'conjuration', classes: ['cleric'],
    castingTime: 'Action', range: 'Self (15-foot Emanation)', components: 'V, S, M (a holy symbol)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'You call forth spirits to protect you. They flit around you in a 15-foot Emanation for the duration. If you are good or neutral, they appear angelic; if evil, fiendish. When you cast this spell, you can designate any number of creatures you can see as allies to be unaffected. An affected creature\'s Speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it makes a Wisdom saving throw, taking 3d8 Radiant damage (or Necrotic if you\'re evil) on a failed save, half on success.',
    atHigherLevels: 'Using a spell slot of level 4+: damage increases by 1d8 for each slot level above 3rd.',
    source: 'PHB 2024 p.328' },
  { id: 'mass_healing_word', name: 'Mass Healing Word', level: 3, school: 'abjuration', classes: ['cleric', 'bard'],
    castingTime: 'Bonus Action', range: '60 feet', components: 'V', duration: 'Instantaneous',
    description: 'Up to six creatures of your choice that you can see within range regain HP equal to 1d4 + your spellcasting ability modifier. This spell has no effect on Constructs or Undead.',
    atHigherLevels: 'Using a spell slot of level 4+: healing increases by 1d4 for each slot level above 3rd.',
    source: 'PHB 2024 p.303' },
  { id: 'protection_from_energy', name: 'Protection from Energy', level: 3, school: 'abjuration', classes: ['cleric', 'wizard', 'sorcerer', 'druid', 'ranger', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S', duration: 'Concentration, up to 1 hour', concentration: true,
    description: 'For the duration, the willing creature you touch has Resistance to one damage type of your choice: Acid, Cold, Fire, Lightning, or Thunder.',
    atHigherLevels: null, source: 'PHB 2024 p.313' },

  // =================================================================
  // LEVEL 4-5 SPELLS (subset — iconic entries)
  // =================================================================
  { id: 'polymorph', name: 'Polymorph', level: 4, school: 'transmutation', classes: ['wizard', 'sorcerer', 'bard', 'druid'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (a caterpillar cocoon)', duration: 'Concentration, up to 1 hour', concentration: true,
    description: 'This spell transforms a creature you can see within range into a new form (Wisdom saving throw to negate for an unwilling target). The transformation lasts for the duration or until the target has 0 HP or dies. The new form can be any Beast with a CR equal to or less than the target\'s CR (or the target\'s level if it doesn\'t have a CR). The target assumes the new form\'s HP, and when it reverts to its normal form, it returns to the HP it had before transformation.',
    atHigherLevels: null, source: 'PHB 2024 p.312' },
  { id: 'greater_invisibility', name: 'Greater Invisibility', level: 4, school: 'illusion', classes: ['wizard', 'sorcerer', 'bard'],
    castingTime: 'Action', range: 'Touch', components: 'V, S', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You or a creature you touch has the Invisible condition for the duration.',
    atHigherLevels: null, source: 'PHB 2024 p.284' },
  { id: 'wall_of_fire', name: 'Wall of Fire', level: 4, school: 'evocation', classes: ['wizard', 'sorcerer', 'druid'],
    castingTime: 'Action', range: '120 feet', components: 'V, S, M (a small piece of phosphorus)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. When the wall appears, each creature in its area makes a Dexterity saving throw, taking 5d8 Fire damage on a failed save, half on a success. One side of the wall (chosen by you) deals 5d8 Fire damage to each creature that ends its turn within 10 feet of that side or inside the wall.',
    atHigherLevels: 'Using a spell slot of level 5+: damage increases by 1d8 for each slot level above 4th.',
    source: 'PHB 2024 p.336' },
  { id: 'guardian_of_faith', name: 'Guardian of Faith', level: 4, school: 'conjuration', classes: ['cleric'],
    castingTime: 'Action', range: '30 feet', components: 'V', duration: '8 hours',
    description: 'A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range. Any creature hostile to you that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw or take 20 Radiant damage. The guardian vanishes when it has dealt a total of 60 damage.',
    atHigherLevels: null, source: 'PHB 2024 p.283' },
  { id: 'freedom_of_movement', name: 'Freedom of Movement', level: 4, school: 'abjuration', classes: ['cleric', 'druid', 'ranger', 'bard', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (a leather strap bound around the arm)', duration: '1 hour',
    description: 'You touch a willing creature. For the duration, the target\'s movement is unaffected by Difficult Terrain, and Spells and other magical effects can neither reduce the target\'s Speed nor cause the target to be Paralyzed or Restrained. The target can also spend 5 feet of movement to automatically escape from nonmagical restraints such as manacles or a creature that has it Grappled.',
    atHigherLevels: null, source: 'PHB 2024 p.279' },
  { id: 'wall_of_force', name: 'Wall of Force', level: 5, school: 'evocation', classes: ['wizard'],
    castingTime: 'Action', range: '120 feet', components: 'V, S, M (a pinch of powder made by crushing a clear gemstone)', duration: 'Concentration, up to 10 minutes', concentration: true,
    description: 'An invisible wall of force springs into existence at a point you choose within range. The wall appears as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a Sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels. Each panel must be contiguous with another panel. Whichever form you choose, the wall is 1/4 inch thick. It lasts for the duration. Nothing can physically pass through it. It is immune to all damage and can\'t be dispelled by Dispel Magic. Disintegrate destroys it.',
    atHigherLevels: null, source: 'PHB 2024 p.335' },
  { id: 'cone_of_cold', name: 'Cone of Cold', level: 5, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Self (60-foot Cone)', components: 'V, S, M (a small crystal or glass cone)', duration: 'Instantaneous',
    description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot Cone makes a Constitution saving throw, taking 8d8 Cold damage on a failed save or half as much on a successful one.',
    atHigherLevels: 'Using a spell slot of level 6+: damage increases by 1d8 for each slot level above 5th.',
    source: 'PHB 2024 p.259' },
  { id: 'mass_cure_wounds', name: 'Mass Cure Wounds', level: 5, school: 'abjuration', classes: ['cleric', 'druid', 'bard'],
    castingTime: 'Action', range: '60 feet', components: 'V, S', duration: 'Instantaneous',
    description: 'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius Sphere centered on that point. Each target regains HP equal to 3d8 + your spellcasting ability modifier. This spell has no effect on Constructs or Undead.',
    atHigherLevels: 'Using a spell slot of level 6+: healing increases by 1d8 for each slot level above 5th.',
    source: 'PHB 2024 p.303' },
  { id: 'raise_dead', name: 'Raise Dead', level: 5, school: 'necromancy', classes: ['cleric', 'bard', 'paladin'],
    castingTime: '1 hour', range: 'Touch', components: 'V, S, M (a diamond worth 500+ GP, which the spell consumes)', duration: 'Instantaneous',
    description: 'You return a dead creature you touch to life, provided that it has been dead no longer than 10 days. If the creature\'s soul is willing and at liberty, the creature comes back to life with 1 HP. This spell closes all mortal wounds but doesn\'t restore missing body parts. It also removes any Poisons and cures any nonmagical Diseases. The revived creature has -4 to attack rolls, saving throws, and ability checks. Every long rest reduces this by 1 until it disappears.',
    atHigherLevels: null, source: 'PHB 2024 p.314' },

  // =================================================================
  // COMMON MISSING SPELLS (Level 0-3) — added on demand
  // =================================================================
  { id: 'catapult', name: 'Catapult', level: 1, school: 'transmutation', classes: ['wizard', 'sorcerer', 'artificer'],
    castingTime: 'Action', range: '60 feet', components: 'S', duration: 'Instantaneous',
    description: 'Choose one object weighing 1 to 5 pounds within range that isn\'t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving; the target takes 3d8 Bludgeoning damage, or half as much on a successful save.',
    atHigherLevels: 'Using a spell slot of level 2+: the object\'s maximum weight increases by 5 lbs and the damage increases by 1d8 for each slot level above 1st.',
    source: 'PHB 2024 p.256' },
  { id: 'absorb_elements', name: 'Absorb Elements', level: 1, school: 'abjuration', classes: ['wizard', 'sorcerer', 'druid', 'ranger', 'artificer'],
    castingTime: 'Reaction, which you take when you take Acid, Cold, Fire, Lightning, or Thunder damage', range: 'Self', components: 'S', duration: '1 round',
    description: 'The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have Resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type.',
    atHigherLevels: 'Using a spell slot of level 2+: the extra damage increases by 1d6 for each slot level above 1st.',
    source: 'PHB 2024 p.240' },
  { id: 'feather_fall', name: 'Feather Fall', level: 1, school: 'transmutation', classes: ['wizard', 'sorcerer', 'bard', 'artificer'],
    castingTime: 'Reaction, which you take when you or a creature within 60 feet falls', range: '60 feet', components: 'V, M (a small feather or piece of down)', duration: '1 minute',
    description: 'Choose up to five falling creatures within range. A falling creature\'s rate of descent slows to 60 feet per round until the spell ends. If a creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature.',
    atHigherLevels: null, source: 'PHB 2024 p.272' },
  { id: 'thunderwave', name: 'Thunderwave', level: 1, school: 'evocation', classes: ['wizard', 'sorcerer', 'bard', 'druid'],
    castingTime: 'Action', range: 'Self (15-foot Cube)', components: 'V, S', duration: 'Instantaneous',
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot Cube originating from you makes a Constitution saving throw. On a failed save, a creature takes 2d8 Thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed. In addition, unsecured objects that are entirely within the Cube are automatically pushed 10 feet away from you, and the spell emits a thunderous boom audible out to 300 feet.',
    atHigherLevels: 'Using a spell slot of level 2+: damage increases by 1d8 for each slot level above 1st.',
    source: 'PHB 2024 p.333' },
  { id: 'command', name: 'Command', level: 1, school: 'enchantment', classes: ['cleric', 'paladin', 'bard'],
    castingTime: 'Action', range: '60 feet', components: 'V', duration: '1 round',
    description: 'You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is Undead, if it doesn\'t understand your language, or if your command is directly harmful to it. Some typical commands: Approach, Drop, Flee, Grovel, Halt.',
    atHigherLevels: 'Using a spell slot of level 2+: you can affect one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other.',
    source: 'PHB 2024 p.258' },
  { id: 'faerie_fire', name: 'Faerie Fire', level: 1, school: 'evocation', classes: ['bard', 'druid', 'cleric'],
    castingTime: 'Action', range: '60 feet', components: 'V', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has Advantage if the attacker can see it, and the affected creature or object can\'t benefit from being Invisible.',
    atHigherLevels: null, source: 'PHB 2024 p.272' },
  { id: 'charm_person', name: 'Charm Person', level: 1, school: 'enchantment', classes: ['wizard', 'sorcerer', 'bard', 'druid', 'warlock'],
    castingTime: 'Action', range: '30 feet', components: 'V, S', duration: '1 hour',
    description: 'You attempt to charm a Humanoid you can see within range. It must make a Wisdom saving throw with Advantage if you or your companions are fighting it. If it fails the save, it is Charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you.',
    atHigherLevels: 'Using a spell slot of level 2+: you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other.',
    source: 'PHB 2024 p.256' },
  { id: 'comprehend_languages', name: 'Comprehend Languages', level: 1, school: 'divination', classes: ['wizard', 'sorcerer', 'bard', 'warlock'],
    castingTime: 'Action or Ritual', range: 'Self', components: 'V, S, M (a pinch of soot and salt)', duration: '1 hour', ritual: true,
    description: 'For the duration, you understand the literal meaning of any language that you hear or see signed. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text. This spell doesn\'t decode secret messages in a text or a glyph that isn\'t part of a written language.',
    atHigherLevels: null, source: 'PHB 2024 p.258' },
  { id: 'identify', name: 'Identify', level: 1, school: 'divination', classes: ['wizard', 'bard', 'artificer'],
    castingTime: '1 minute or Ritual', range: 'Touch', components: 'V, S, M (a pearl worth 100+ GP and an owl feather)', duration: 'Instantaneous', ritual: true,
    description: 'You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement, and how many Charges it has, if any. You learn whether any Spells are affecting the item and what they are. Alternatively, you can touch a creature and learn what Spells, if any, are currently affecting it.',
    atHigherLevels: null, source: 'PHB 2024 p.293' },
  { id: 'longstrider', name: 'Longstrider', level: 1, school: 'transmutation', classes: ['wizard', 'druid', 'bard', 'ranger', 'artificer'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (a pinch of dirt)', duration: '1 hour',
    description: 'You touch a creature. The target\'s Speed increases by 10 feet until the spell ends.',
    atHigherLevels: 'Using a spell slot of level 2+: you can target one additional creature for each slot level above 1st.',
    source: 'PHB 2024 p.300' },
  { id: 'flaming_sphere', name: 'Flaming Sphere', level: 2, school: 'evocation', classes: ['wizard', 'druid'],
    castingTime: 'Action', range: '60 feet', components: 'V, S, M (a bit of tallow, a pinch of brimstone, and a dusting of powdered iron)', duration: 'Concentration, up to 1 minute', concentration: true,
    description: 'A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 Fire damage on a failed save, or half as much on a successful one. As a Bonus Action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature makes the saving throw. The sphere ignites flammable objects not being worn or carried, and it sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet.',
    atHigherLevels: 'Using a spell slot of level 3+: damage increases by 1d6 for each slot level above 2nd.',
    source: 'PHB 2024 p.279' },
  { id: 'hunters_mark', name: 'Hunter\'s Mark', level: 1, school: 'divination', classes: ['ranger'],
    castingTime: 'Bonus Action', range: '90 feet', components: 'V', duration: 'Concentration, up to 1 hour', concentration: true,
    description: 'You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 Force damage to the target whenever you hit it with an attack roll, and you have Advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 HP before the spell ends, you can use a Bonus Action on a later turn to mark a new creature.',
    atHigherLevels: 'Using a spell slot of level 3-4: you can maintain your concentration for up to 8 hours. Using a level 5+: up to 24 hours.',
    source: 'PHB 2024 p.293' },
  { id: 'aid_2024', name: 'Warding Bond', level: 2, school: 'abjuration', classes: ['cleric', 'paladin'],
    castingTime: 'Action', range: 'Touch', components: 'V, S, M (a pair of platinum rings worth 50+ GP each, which you and the target must wear for the duration)', duration: '1 hour',
    description: 'You touch a willing creature and forge a mystic connection. While the target is within 60 feet of you, it gains a +1 bonus to AC and Saving Throws, and it has Resistance to all damage. Also, each time it takes damage, you take the same amount of damage. The spell ends if you drop to 0 HP or if the target is more than 60 feet from you.',
    atHigherLevels: null, source: 'PHB 2024 p.336' },

  // =================================================================
  // ICONIC HIGHER-LEVEL SPELLS (6-9)
  // =================================================================
  { id: 'meteor_swarm', name: 'Meteor Swarm', level: 9, school: 'evocation', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: '1 mile', components: 'V, S', duration: 'Instantaneous',
    description: 'Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius Sphere centered on each point you choose must make a Dexterity saving throw. The Sphere spreads around corners. A creature takes 20d6 Fire damage and 20d6 Bludgeoning damage on a failed save, or half as much on a successful one. The spell damages objects in the area and ignites flammable objects that aren\'t being worn or carried. If you choose points of impact that are less than 40 feet apart, you can strike a single area with multiple orbs.',
    atHigherLevels: null, source: 'PHB 2024 p.304' },
  { id: 'wish', name: 'Wish', level: 9, school: 'conjuration', classes: ['wizard', 'sorcerer'],
    castingTime: 'Action', range: 'Self', components: 'V', duration: 'Instantaneous',
    description: 'Wish is the mightiest spell a mortal can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use is to duplicate any other spell of 8th level or lower. Alternatively, you may create an object worth 25,000 GP or less, grant creatures resistance to a damage type for 8 hours, and so on. See PHB for the full effect list and the strain penalty for using non-duplicate effects.',
    atHigherLevels: null, source: 'PHB 2024 p.339' },
  { id: 'true_resurrection', name: 'True Resurrection', level: 9, school: 'necromancy', classes: ['cleric', 'druid'],
    castingTime: '1 hour', range: 'Touch', components: 'V, S, M (holy water and diamonds worth 25,000+ GP, which the spell consumes)', duration: 'Instantaneous',
    description: 'You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age. If the creature\'s soul is free and willing, the creature is restored to life with all its HP.',
    atHigherLevels: null, source: 'PHB 2024 p.334' }

];

// Flat lookup by id
const SPELLS_BY_ID = SPELLS_2024.reduce(function(m, s) { m[s.id] = s; return m; }, {});

// Grouped by level for the picker
const SPELLS_BY_LEVEL = SPELLS_2024.reduce(function(m, s) {
  if (!m[s.level]) m[s.level] = [];
  m[s.level].push(s);
  return m;
}, {});
