#!/usr/bin/env python3
"""
Sync Firebase /monster-homebrew into the Obsidian vault as .md files.

Everything the DM adds via the in-app Custom Monster form lands in
Firebase Realtime DB. This script fetches that state and writes one
.md file per monster into:

  /Discovery D_D/Eldoria 2.0/Bestiary/from-app/

Files there are treated as auto-generated:
  - Overwritten on every run (Firebase is source of truth)
  - Deleted if their monster is gone from Firebase
  - Not hand-edited (edit in-app, then re-run this)

Reads Firebase via the public REST endpoint — no credentials needed
because /monster-homebrew has open .read rules.

Usage:
  python3 tools/backup_monsters_to_vault.py [--out PATH]
"""
import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

FIREBASE_URL = 'https://wayward-company-default-rtdb.asia-southeast1.firebasedatabase.app/monster-homebrew.json'
DEFAULT_OUT = Path(
    '/Users/Brad/Library/CloudStorage/OneDrive-WAVERLEYCHRISTIANCOLLEGE/'
    'D_D/Discovery D_D/Eldoria 2.0/Bestiary/from-app'
)

README_TEXT = '''---
title: Bestiary — From-App (auto-sync)
type: reference
tags: [bestiary, auto-generated, do-not-edit]
---

# Bestiary — From-App (auto-sync)

> **Do not hand-edit files in this folder.** Every `.md` here is auto-generated by `tools/backup_monsters_to_vault.py` from the live Firebase `/monster-homebrew` state.
>
> If you edit a file here, your changes will be overwritten the next time the backup script runs.

## How to add / edit a monster

1. Open the DM site → Combat → 📖 Add from catalog → **+ Create custom** (or ✎ Edit any existing entry).
2. Save. It syncs to Firebase immediately.
3. Run `python3 tools/regenerate_all.py` (or just this script directly) — the corresponding `.md` file appears / updates here.

## How to remove a monster from the vault

Delete it in-app via the ✕ Delete button. Next backup run removes the `.md` file automatically.

## Why this folder exists

The Bestiary parent folder is for your hand-authored lore and canonical creatures. This subfolder is a mirror of the in-app catalog so everything you type into the tracker is git-tracked and searchable in Obsidian.
'''


def slugify(text: str) -> str:
    s = re.sub(r'[^a-zA-Z0-9\- ]+', '', str(text or 'unnamed')).strip()
    s = re.sub(r'\s+', ' ', s)
    return s or 'unnamed'


def to_yaml_scalar(v):
    """Quote scalars conservatively for YAML frontmatter."""
    if v is None:
        return '""'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    # Quote if it contains anything that could confuse YAML
    if any(c in s for c in ':#&*!|>%@`\'"\n{}[],'):
        return json.dumps(s, ensure_ascii=False)
    return json.dumps(s, ensure_ascii=False) if not s.strip() else s


def monster_to_md(mid: str, m: dict) -> str:
    lines = ['---', f'id: {mid}']
    # Simple scalar fields first
    for key in ['name','size','type','alignment','ac','acNote','hp','hpFormula','speed',
                'str','dex','con','int','wis','cha',
                'damageResist','damageImmune','damageVuln','conditionImmune',
                'senses','languages','cr','xp','role','source']:
        v = m.get(key)
        if v is None or v == '' or v == []:
            continue
        if isinstance(v, list):
            lines.append(f'{key}: {json.dumps(v, ensure_ascii=False)}')
        elif isinstance(v, dict):
            lines.append(f'{key}: {json.dumps(v, ensure_ascii=False)}')
        else:
            lines.append(f'{key}: {to_yaml_scalar(v)}')
    # Environment list
    env = m.get('environment')
    if isinstance(env, list) and env:
        lines.append(f'environment: {json.dumps(env, ensure_ascii=False)}')
    # Saves / skills (nested)
    for nested in ['saves','skills']:
        v = m.get(nested)
        if isinstance(v, dict) and v:
            lines.append(f'{nested}: {json.dumps(v, ensure_ascii=False)}')
    # Traits / actions / etc — list of {name, desc}
    for block_key in ['traits','actions','bonusActions','reactions','legendaryActions']:
        blocks = m.get(block_key)
        if not isinstance(blocks, list) or not blocks:
            continue
        lines.append(f'{block_key}:')
        for b in blocks:
            if isinstance(b, dict):
                name = json.dumps(b.get('name', ''), ensure_ascii=False)
                desc = json.dumps(b.get('desc', ''), ensure_ascii=False)
                lines.append(f'  - name: {name}')
                lines.append(f'    desc: {desc}')
    lines.append('---')
    lines.append('')
    lines.append(f'# {m.get("name", mid)}')
    lines.append('')
    lines.append('_Auto-generated from Firebase. Edit in-app, not here._')
    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    # Write / refresh the README
    readme = args.out / '_README.md'
    readme.write_text(README_TEXT, encoding='utf-8')

    # Fetch Firebase state
    try:
        with urllib.request.urlopen(FIREBASE_URL, timeout=15) as r:
            data = json.loads(r.read().decode('utf-8')) or {}
    except Exception as e:
        sys.exit(f'! Failed to fetch Firebase: {e}')

    # Write .md for each monster, track live set
    live_stems = {'_README'}
    for mid, m in (data.items() if isinstance(data, dict) else []):
        if not isinstance(m, dict):
            continue
        name = m.get('name') or mid
        stem = slugify(name)
        live_stems.add(stem)
        path = args.out / f'{stem}.md'
        path.write_text(monster_to_md(mid, m), encoding='utf-8')

    # Remove stale .md files (monsters deleted in-app)
    removed = 0
    for existing in args.out.glob('*.md'):
        if existing.stem not in live_stems:
            existing.unlink()
            removed += 1

    print(f'Backup complete: {len(data) if isinstance(data, dict) else 0} monsters written, {removed} stale files removed.')
    print(f'Location: {args.out}')


if __name__ == '__main__':
    main()
